### PR TITLE
Support for Raspberry Pi and other architectures

### PR DESCRIPTION
**Pull request by lpabon**

### CODE REVIEW

**Comment by lpabon** [comment]
Closes #627

**Comment by lpabon** [comment]
# New Makefile

```
(heketi) lpabon@localhost : ~/git/golang/heketi/src/github.com/heketi/heketi
$ cd dist/

(heketi) lpabon@localhost : ~/git/golang/heketi/src/github.com/heketi/heketi/dist
$ ls -al
total 71940
drwxrwxr-x.  2 lpabon lpabon     4096 Jan 21 21:44 .
drwxrwxr-x. 16 lpabon lpabon     4096 Jan 21 21:44 ..
-rw-rw-r--.  1 lpabon lpabon  7525877 Jan 21 21:42 heketi-client-v3.0.0-96-g131e741-rpi.darwin.amd64.tar.gz
-rw-rw-r--.  1 lpabon lpabon  7549639 Jan 21 21:44 heketi-client-v3.0.0-96-g131e741-rpi.linux.amd64.tar.gz
-rw-rw-r--.  1 lpabon lpabon  6800128 Jan 21 21:43 heketi-client-v3.0.0-96-g131e741-rpi.linux.arm.tar.gz
-rw-rw-r--.  1 lpabon lpabon 17763953 Jan 21 21:42 heketi-v3.0.0-96-g131e741-rpi.darwin.amd64.tar.gz
-rw-rw-r--.  1 lpabon lpabon 17892153 Jan 21 21:44 heketi-v3.0.0-96-g131e741-rpi.linux.amd64.tar.gz
-rw-rw-r--.  1 lpabon lpabon 16110627 Jan 21 21:43 heketi-v3.0.0-96-g131e741-rpi.linux.arm.tar.gz

(heketi) lpabon@localhost : ~/git/golang/heketi/src/github.com/heketi/heketi/dist
$ tar xzvf heketi-v3.0.0-96-g131e741-rpi.darwin.amd64.tar.gz
heketi/
heketi/heketi
heketi/heketi-cli
heketi/heketi.json

(heketi) lpabon@localhost : ~/git/golang/heketi/src/github.com/heketi/heketi/dist
$ file heketi/heketi
heketi/heketi: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS>

(heketi) lpabon@localhost : ~/git/golang/heketi/src/github.com/heketi/heketi/dist
$ tar xzvf heketi-v3.0.0-96-g131e741-rpi.linux.arm.tar.gz
heketi/
heketi/heketi
heketi/heketi-cli
heketi/heketi.json

(heketi) lpabon@localhost : ~/git/golang/heketi/src/github.com/heketi/heketi/dist
$ file heketi/heketi
heketi/heketi: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped
```

# Creating a docker image for RPi

```
$ ./build-rpi-dockerfile.sh
godep go build -ldflags "-X main.HEKETI_VERSION=v3.0.0-97-g7a78dde-rpi -extldflags '-z relro -z now'" -o heketi
make[1]: Entering directory '/home/lpabon/git/golang/heketi/src/github.com/heketi/heketi/client/cli/go'
godep go build -ldflags "-X main.HEKETI_CLI_VERSION=v3.0.0-97-g7a78dde-rpi -extldflags '-z relro -z now'" -o heketi-cli
make[1]: Leaving directory '/home/lpabon/git/golang/heketi/src/github.com/heketi/heketi/client/cli/go'
Cleaning Workspace...
rm -rf heketi
rm -rf dist
make[1]: Entering directory '/home/lpabon/git/golang/heketi/src/github.com/heketi/heketi/client/cli/go'
Cleaning Workspace...
rm -rf heketi-cli
rm -rf dist
make[1]: Leaving directory '/home/lpabon/git/golang/heketi/src/github.com/heketi/heketi/client/cli/go'
Sending build context to Docker daemon 73.54 MB
Step 1 : FROM resin/rpi-raspbian
 ---> e49ffb0714c7
Step 2 : MAINTAINER Luis Pabón <luis.pabon@coreos.com>
 ---> Using cache
 ---> 0daaa71293b9
Step 3 : LABEL version "1.0.0"
 ---> Using cache
 ---> 6b8ab992f6c4
Step 4 : LABEL description "Heketi Container for Raspberry Pi"
 ---> Using cache
  --> d4ec2e8e10de
Step 5 : ADD ./heketi /usr/bin/heketi
 ---> Using cache
 ---> e2908f289883
Step 6 : ADD ./heketi-cli /usr/bin/heketi-cli
 ---> Using cache
 ---> 064f7dc91425
Step 7 : ADD ./heketi.json /etc/heketi/heketi.json
 ---> Using cache
 ---> 63fbf42883a5
Step 8 : VOLUME /etc/heketi
 ---> Using cache
 ---> 4ed14d69ee25
Step 9 : VOLUME /var/lib/heketi
 ---> Running in 33b652c364de
 ---> 9d40526033ef
Removing intermediate container 33b652c364de
Step 10 : ENTRYPOINT /usr/bin/heketi
 ---> Running in da216b289812
 ---> 6175af64135c
Removing intermediate container da216b289812
Step 11 : EXPOSE 8080
 ---> Running in 2d8e64de4464
 ---> 2ba594f09c92
Removing intermediate container 2d8e64de4464
Step 12 : CMD -config=/etc/heketi/heketi.json
 ---> Running in c9d166a7b031
 ---> 3bfbd1bda641
Removing intermediate container c9d166a7b031
Successfully built 3bfbd1bda64
```

# Testing Heketi on Kubernetes on RPi Cluster

```

lpabon@localhost : ~/git/containers/rpi
$ alias kk='kubectl'

lpabon@localhost : ~/git/containers/rpi
$ kk --kubeconfig=rpi-admin.conf run heketi-rpi --image=heketi/heketi-rpi --port=8080
deployment "heketi-rpi" created

lpabon@localhost : ~/git/containers/rpi
$ kk --kubeconfig=rpi-admin.conf get pods
NAME                          READY     STATUS              RESTARTS   AGE
heketi-rpi-4199268929-wkc93   0/1       ContainerCreating   0          7s
rpi-pause-2739229123-jmv5m    1/1       Running             0          23h

lpabon@localhost : ~/git/containers/rpi
$ kk --kubeconfig=rpi-admin.conf get pods
NAME                          READY     STATUS              RESTARTS   AGE
heketi-rpi-4199268929-wkc93   0/1       ContainerCreating   0          15s
rpi-pause-2739229123-jmv5m    1/1       Running             0          23h

lpabon@localhost : ~/git/containers/rpi
$ kk --kubeconfig=rpi-admin.conf get pods
NAME                          READY     STATUS    RESTARTS   AGE
heketi-rpi-4199268929-wkc93   1/1       Running   0          1m
rpi-pause-2739229123-jmv5m    1/1       Running   0          23h

lpabon@localhost : ~/git/containers/rpi
$ kk --kubeconfig=rpi-admin.conf get pod heketi-rpi-4199268929-wkc93 -o yaml | grep image
  - image: heketi/heketi-rpi
    imagePullPolicy: Always
    image: heketi/heketi-rpi
    imageID: docker-pullable://heketi/heketi-rpi@sha256:fae0dc9237bae3f87cd7078ac8862dd1050cb60b88c8cc61957ac711e8a28f08
```

**Comment by lpabon** [comment]
@heketi/dev Please check out

**Comment by ravishivt** [comment]
While this is awesome and gets images built for Raspberry Pi, I have a couple concerns.  One is that you have to build the image directly on a Raspberry Pi, which could lead to delayed releases.  Second, only Raspberry Pi's `arm` / `aarch32`architecture  is supported.

Take a look at [hypercube's Makefile](https://github.com/kubernetes/kubernetes/blob/master/build/pause/Makefile).  It uses QEMU to build cross-platform docker images on a standard arm64 server.

I'm fine with merging this PR and moving to a cleaner approach in the future.  I might get some cycles to work on that.

**Comment by lpabon** [comment]
@ravishivt This change does not need to build the image on a RPi.  Take a look at https://github.com/heketi/heketi/pull/658/files#diff-3c6b40c021ea51225aac50b4f3ae21ba .  With this change, the docker images will be built automatically by Quay.io or Docker Hub

**Comment by ravishivt** [comment]
You are correct.  I just successfully built the RPI image on my laptop.  Looking at the Dockerfile, there are no `RUN` statements which is why it works without QEMU I believe.

I can't see where this PR builds `arm64` images.  I see it builds 64-bit binaries but in order to build `arm64` images, we'd need a Dockerfile that uses an `aarch64` base image, possibly `aarch64/debian` from https://hub.docker.com/u/aarch64/.  RPI3 is a 64-bit capable board but the raspbian OS is 32-bit.  A templated Dockerfile might be an option that just substitutes the base image accordingly.

**Comment by lpabon** [comment]
@ravishivt Ah, yeah, we could make docker containers for arm64.  I think we can leave that for another PR.

**Pull request merged**
