### PR TITLE
Adding serviceaccount for openshift deploy

### PR DESCRIPTION
**Pull request by ghamed**
Hi,

This is for fixing the issue with deploying heketi on openshift when using dedicated storage. The following issue is also raised https://github.com/heketi/heketi/issues/909 .

Regards,

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
@ghamed reviewing this. I will get back to you soon.

**Comment by jarrpa** [comment]
Howdy! Thanks for the PR. :)

Unfortunately, this is not quite adequate. The name `heketi-storage-service-account` is dynamically generated and will not always be fixed. The right fix would be to detect and use the ServiceAccount from the deploy-heketi pod.

**Comment by obnoxxx** [comment]
Hi, what's the situation with this PR? The last comment by @jarrpa seems to indicate that this change is not the correct fix. Do we want to update this PR for a different change or can we close it? @ghamed? Thanks!

**Comment by ghamed** [comment]
Hi,

Sorry for the late reply, I agree with @jarrpa and this needs more thought to be honest.

**Pull request closed without merging**
