### PR TITLE
return if unable to retrieve entry from db

### PR DESCRIPTION
**Pull request by raghavendra-talur**
This is fix for a crash in SetState when a null node entry is passed.

Signed-off-by: Raghavendra Talur <rtalur@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
ok to test @centos-ci

**Comment by obnoxxx** [comment]
Thanks, @raghavendra-talur, this change looks correct, good catch!

Could we think about a test for this?

**Comment by obnoxxx** [comment]
test this please

**Comment by obnoxxx** [comment]
please test @centos-ci

**Comment by obnoxxx** [comment]
i never can remember the magic words... :-o

**Comment by MohamedAshiqrh** [comment]
he he :P

**Comment by raghavendra-talur** [comment]
@obnoxxx added a test. Test caused the same crash as seen before without the fix and no crash seen after the fix.

```
github.com/heketi/heketi/apps/glusterfs.(*NodeEntry).SetState(0x0, 0xc420168f00, 0x24948c0, 0xc420295380, 0x248ed20, 0xc4201690e0, 0xc420316e08, 0x7, 0x47a262, 0x599c9888)
	/home/rtalur/Code/go/src/github.com/heketi/heketi/apps/glusterfs/node_entry.go:301 +0x57
github.com/heketi/heketi/apps/glusterfs.(*App).NodeSetState.func2(0xed12e8f88, 0x2b8a3bb3, 0x24edfa0, 0xc4204a5790)
	/home/rtalur/Code/go/src/github.com/heketi/heketi/apps/glusterfs/app_node.go:360 +0x80
github.com/heketi/heketi/vendor/github.com/heketi/rest.(*AsyncHttpManager).AsyncHttpRedirectFunc.func1(0xc420389580, 0xc420011740)
	/home/rtalur/Code/go/src/github.com/heketi/heketi/vendor/github.com/heketi/rest/asynchttp.go:128 +0xf4
,created by github.com/heketi/heketi/vendor/github.com/heketi/rest.(*AsyncHttpManager).AsyncHttpRedirectFunc
	/home/rtalur/Code/go/src/github.com/heketi/heketi/vendor/github.com/heketi/rest/asynchttp.go:138 +0x60
Error: Tests failed.
```

**Comment by obnoxxx** [comment]
@raghavendra-talur the centos-ci test failed

**Comment by obnoxxx** [comment]
retest this please @centos-ci

**Comment by humblec** [comment]
@raghavendra-talur as per our discussion couple of days back the test failure is due to some other issues and not specifc to this patch. Can you please update the details here , so that we can move ahead on this PR ?

**Comment by obnoxxx** [comment]
This definitely does not look related to the patch.
I also don't understand the error message - there is no file `tests/functional/go/test/fixedbugs/bug050.go` in heketi... :-o
That being said, other PRs do successfully run the tests, so there seems to be some relationship after all which I don't understand. I can't run the tests locally either currently, because the functional tests are broken on my machine in general (see the heketi-devel thread...).

**Comment by raghavendra-talur** [comment]
This is failing CI because of golang version. Heketi build itself fails. On my machine with golang 1.8 I am able to build heketi and the TestSmokeTest completely passes.

```
[negroni] Completed 200 OK in 468.304µs
PASS
ok      github.com/heketi/heketi/tests/functional/TestSmokeTest/tests   636.166s
Shutting down...
[heketi] INFO 2017/09/01 16:15:17 Closed
```

I suggest that we merge this patch and find a way to have higher version of golang on CI machines.

**Comment by obnoxxx** [comment]
thanks @raghavendra-talur , since the patch LGTM, i'm merging.

**Pull request merged**
