### PR TITLE
app: save bricks in allocBricks() to keep the db consistent

### LINKED ISSUE #382: topology info: "ID not found" error when running concurrently with volume creation.
heketi-cli topology info
Error: Id not found

Logs:
[negroni] Started GET /volumes/1819834f5be2c3dce81b36e14ea440c0
[negroni] Completed 200 OK in 761.725µs
[negroni] Started GET /nodes/410b2c68b6df188f88a69003cb8a757b
[negroni] Completed 500 Internal Server Error in 6.36837ms

500 when fetching node information. As of now not sure why it's failing when running parallely.

### PR DESCRIPTION
**Pull request by obnoxxx**
Earlier, the bricks were only saved to the DB in volume.Create.

Closes #382

Pair-Programmed-With: Raghavendra Talur <rtalur@redhat.com>
Pair-Programmed-With: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

Signed-off-by: Michael Adam <obnox@redhat.com>
Signed-off-by: Raghavendra Talur <rtalur@redhat.com>
Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
There are issues. Gonna fix up an resubmit...

**Comment by obnoxxx** [comment]
Okay... that's strange: The travis tests fail at apps/glusterfs/volume_entry_test.go:607. But on my machine it succeeds... :-o

**Comment by obnoxxx** [comment]
oops, i was testing the wrong branch. the error is real.

**Comment by lpabon** [comment]
And that is why it fails at https://github.com/heketi/heketi/blob/master/apps/glusterfs/volume_entry_test.go#L607 . Because the brickpath has been saved to the database before the path has been set during brick creation.

**Comment by lpabon** [comment]
There also should be a new test added which replicates the issue #382 and shows how this patch fixes it.

**Comment by obnoxxx** [comment]
updated the patch so that it should pass tests now.
will work on providing a unit test.... need to figure out how to best to it

**Comment by obnoxxx** [comment]
Updated the PR with an additional patch that adds a test for issue #382. When the fix patch is reverted, the test fails.

**Comment by obnoxxx** [comment]
@raghavendra-talur In the actual fix, we needed to keep the saving of bricks in VolumeEntry.Create(), because the CreateBricks() at line 333 actually fills the brick with info. So we need to store twice: once in allocBricks so that the device and volume structures are not pointing into nirvana, and once after CreateBricks() to store the actual brick data.

**Comment by obnoxxx** [comment]
Updated the PR with fixed formatting in the test (go fmt ...)...
(Warning @lpabon : Did an amended patch for this... ;-) )

**Pull request merged**
