### PR TITLE
WIP: Test kube

### PR DESCRIPTION
**Pull request by lpabon**

### CODE REVIEW

**Comment by lpabon** [comment]
ok to test

**Comment by lpabon** [comment]
retest this please

**Comment by lpabon** [comment]
retest this please

**Comment by lpabon** [comment]
retest this please

**Comment by obnoxxx** [comment]
This is a very strange PR without description and without useful commit messages. @lpabon what is this all about?

**Comment by lpabon** [comment]
Oh yeah, sorry... I'm fixing the Kubernetes functional tests and the only way to test the CI is to create a PR :) . It is almost complete, I'll be adding this soon.  I fixed the other non-kubernetes tests last week.

**Comment by lpabon** [comment]
This PR removes the minikube tests, which made it hard to really test GlusterFS, and now we will have a real 3 node cluster with one extra raw disk for GlusterFS.

**Comment by obnoxxx** [comment]
@lpabon aaah, that makes sense. :-)  So I assume you will polish the commit(s) and submit a new PR for merging and review when it's done?

**Comment by lpabon** [comment]
@obnoxxx Absolutely

**Comment by lpabon** [comment]
retest this please

**Comment by lpabon** [comment]
Closed by #833

**Pull request closed without merging**
