### PR TITLE
Heketi-cli: CI test for heketi-cli

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
@lpabon can you look into the error Travis CI build failure(https://travis-ci.org/heketi/heketi/jobs/135848624)? It is pass the local build(https://travis-ci.org/MohamedAshiqrh/heketi). please let me know if I am missing something.

**Comment by lpabon** [comment]
Sure, I won't have time today, but I will make sure to look at it tomorrow.

**Comment by lpabon** [comment]
@MohamedAshiqrh Does this replace #310 ?

**Comment by MohamedAshiqrh** [comment]
@lpabon yeah

**Comment by lpabon** [comment]
Moving to Release 4

**Comment by lpabon** [comment]
I'm closing this since it has been more than 6 months.

**Pull request closed without merging**
