### PR TITLE
Add a python script to fixup orphan bricks

### PR DESCRIPTION
**Pull request by metal3d**
Method is not that easy, the README describes the entire procedure to be able to fixup a database

TODO: maybe better describe the LVM manipulation

### CODE REVIEW

**Comment by obnoxxx** [comment]
@metal3d thanks for your patch! That's great!
Will do a proper review early next week.

**Comment by metal3d** [comment]
I should make some unit tests

**Comment by obnoxxx** [comment]
@metal3d apologies, I'm afraid we will need a few more days, for a thorough review, since we're currently in a rush finishing the stability fixes...

**Comment by metal3d** [comment]
No problem. Take the Time to make it great 😉

**Comment by phlogistonjohn** [comment]
This concept behind this feature was incorporated into heketi proper a while back. I'm pretty sure this script inspired that work. However, this is no longer strictly needed since Heketi 6. Thanks so much for the contribution.

**Pull request closed without merging**
