### PR TITLE
check error in unit test cases

### PR DESCRIPTION
**Pull request by Madhu-1**
check error in unit test cases

Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
ok to test

**Comment by obnoxxx** [comment]
retest this please

**Comment by Madhu-1** [comment]
@obnoxxx  somehow I missed those checks. now added

**Comment by Madhu-1** [comment]
@obnoxxx  looking for other files,   until then please don't merge

**Comment by Madhu-1** [comment]
@obnoxxx  please review, covered remaining files.

**Comment by Madhu-1** [comment]
@obnoxxx as per commit message squashed multiple commits.

**Comment by obnoxxx** [comment]
retest this please

(a problem in the centos ci with yum repos)

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
centos-ci has network problems...

**Pull request merged**
