### PR TITLE
functional tests: check device & node removes work during throttle

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Add a test to verify that throttling works cleanly when
encountering a "busy system" returning throttle errors.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
retest this please

**Comment by phlogistonjohn** [comment]
retest this please

**Comment by phlogistonjohn** [comment]
Test appears to be failing because it is taking >1hr to run, but I don't think its stuck. Will push a change to bump up the timeout a bit.

**Comment by raghavendra-talur** [comment]
@phlogistonjohn the timeout is in jenkins. I am trying to figure out the patch in https://github.com/gluster/glusterfs-patch-acceptance-tests/tree/master/centos-ci/heketi-functional

**Pull request merged**
