### PR TITLE
Deps tarball

### PR DESCRIPTION
**Pull request by obnoxxx**
Create a dependencies tarball.

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
I still get something like heketi-deps-v5.0.0-10-g89abc968-release5.tar.gz on my release branch. I don't understand changes made with VERSION part. Rest looks good.

**Comment by obnoxxx** [comment]
@raghavendra-talur correct, because the version tag `v5.0.0` is not at the branch head...
but instead 8 patches deep in. if you add a tag to the top commit, then `make version` will show exactly the tag.

**Comment by obnoxxx** [comment]
Thinking of this, I guess i should disambiguate "TAG" in case there are multiple tags on the HEAD.

**Comment by obnoxxx** [comment]
updated to only consider version tags (vA.B.C) and to always pick the newest tag when there are multiple tags on HEAD.

**Comment by obnoxxx** [comment]
strange and unrelated failure of centos-ci run.

**Pull request merged**
