### PR TITLE
Fix lint issues

### PR DESCRIPTION
**Pull request by Madhu-1**
### What does this PR achieve? Why do we need it?
This PR fixes issues found in `gofmt` and correct misspelled word. 
### Does this PR fix issues?

Fixes #

### CODE REVIEW

**Comment by Madhu-1** [comment]
>ok  	github.com/heketi/heketi/tests/functional/TestDbExportImport	0.107s
ERROR: failing tests:
  ./tests/020-gofmt.sh
Makefile:100: recipe for target 'test' failed
make: *** [test] Error 1
The command "if [[ -z "$COVERAGE" ]]; then make test TESTOPTIONS=-v ; else make test TESTOPTIONS=-vcstdout && bash .travis-coverage; fi" exited with 2. 

CI failure, but am `make test` passes for me locally

```
  py27: commands succeeded
  py35: commands succeeded
  py36: commands succeeded
  congratulations :)
---- Terminating heketi server, pid=22100
make[1]: Entering directory '/home/mrajanna/workspace/src/github.com/heketi/heketi'
go build  -ldflags "-X main.HEKETI_VERSION=v8.0.0-155-g22091a0-fix-report -extldflags '-z relro -z now'" -o heketi
make[2]: Entering directory '/home/mrajanna/workspace/src/github.com/heketi/heketi/client/cli/go'
go build  -ldflags "-X main.HEKETI_CLI_VERSION=v8.0.0-155-g22091a0-fix-report -extldflags '-z relro -z now'" -o heketi-cli
make[2]: Leaving directory '/home/mrajanna/workspace/src/github.com/heketi/heketi/client/cli/go'
make[1]: Leaving directory '/home/mrajanna/workspace/src/github.com/heketi/heketi'
DB exported to db.json.new
=== RUN   TestSimpleCluster
[heketi] INFO 2018/12/17 19:24:52 Loaded mock executor
[heketi] INFO 2018/12/17 19:24:52 Block: Auto Create Block Hosting Volume set to true
[heketi] INFO 2018/12/17 19:24:52 Block: New Block Hosting Volume size 1100 GB
[heketi] INFO 2018/12/17 19:24:52 GlusterFS Application Loaded
[heketi] INFO 2018/12/17 19:24:52 Closed
--- PASS: TestSimpleCluster (0.02s)
=== RUN   TestLeakPendingVolumeCreate
[heketi] INFO 2018/12/17 19:24:52 Loaded mock executor
[heketi] INFO 2018/12/17 19:24:52 Block: Auto Create Block Hosting Volume set to true
[heketi] INFO 2018/12/17 19:24:52 Block: New Block Hosting Volume size 1100 GB
[heketi] INFO 2018/12/17 19:24:52 GlusterFS Application Loaded
[heketi] INFO 2018/12/17 19:24:52 Allocating brick set #0
[heketi] INFO 2018/12/17 19:24:52 Closed
--- PASS: TestLeakPendingVolumeCreate (0.02s)
PASS
ok  	github.com/heketi/heketi/tests/functional/TestDbExportImport	0.115s
all tests passed
```

**Comment by obnoxxx** [comment]
@Madhu-1 #1461 got merged, so you should rebase on top of latest master, dropping the hunk in `TestAppBlockSettings()`.

**Comment by Madhu-1** [comment]
@obnoxxx @phlogistonjohn PTAL

**Comment by Madhu-1** [comment]
@phlogistonjohn as these changes done as part of running one command, I haven't split into multiple commits.
I will look into adding a script to do this check.

**Comment by phlogistonjohn** [comment]
> phlogistonjohn as these changes done as part of running one command, I haven't split into multiple commits.

No worries, this was small enough to cope with. Just something to think about if the patch became larger.

> I will look into adding a script to do this check.

Please file a PR for that when you are ready, thanks!

**Pull request merged**
