### PR TITLE
Node Remove: Removes all the device in the node

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Node Remove is called to migrate all the bricks in device associated to a node.

Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
All tests are passing in my local. I am not able to open the travis page. Please take a look.

**Comment by MohamedAshiqrh** [comment]
@lpabon @obnoxxx PTAL

**Comment by MohamedAshiqrh** [comment]
@heketi/dev Please review

**Comment by MohamedAshiqrh** [comment]
Thanks for the quick review.

**Comment by lpabon** [comment]
Closes #635

**Comment by wernergillmer** [comment]
This still fails for me. I upgraded to the latest heketi docker image tag 5 and even tried the dev tag
and I still encounter the problem where I cannot remove a device.

    ➜  gluster (master) ✗ heketi-cli device disable 959e5700b171477dd9252546f68c3cd1
    Device 959e5700b171477dd9252546f68c3cd1 is now offline
    ➜  gluster (master) ✗ heketi-cli device delete 959e5700b171477dd9252546f68c3cd1
    Error: Unable to delete device [959e5700b171477dd9252546f68c3cd1] because it contains bricks
    ➜  gluster (master) ✗ heketi-cli device delete 959e5700b171477dd9252546f68c3cd1 force
    Error: Unable to delete device [959e5700b171477dd9252546f68c3cd1] because it contains bricks

**Pull request merged**
