### PR TITLE
executors: use a default error value in the mock executor

### PR DESCRIPTION
**Pull request by phlogistonjohn**
### What does this PR achieve? Why do we need it?

The mock executor treated every executor call as a "silent success" by
    default. This ran contrary to the way the error injection executor
    was making use of the mock executor. Add a default error value to the
    mock executor, defaulting to nil, that is returned by all the default
    executor functions.

Now that the mock executor can return a per-instance default value for
    all errors on non-overridden functions, set the default error to the
    not-supported sentinel error needed by the exec stack. Now, the mock
    functions do not need to be all individually specified in the error
    injection executor.

This all should make adding new functions to the executor system less error prone in the future.

### Notes for the reviewer

This builds upon the work in PR #1724 - please review and merge that first.

### CODE REVIEW

**Comment by pkalever** [comment]
@phlogistonjohn what was the recent change?

**Comment by pkalever** [comment]
> @phlogistonjohn what was the recent change?

Ignore, had noticed it myself now.

**Comment by phlogistonjohn** [comment]
@raghavendra-talur this should only affect test code, its out of date but approved, should we merge or drop this?

**Comment by iamniting** [comment]
I think this can be merged as this is approved and does not require any extra work other than rebasing.

**Review by iamniting — APPROVED** [review]

**Comment by phlogistonjohn** [comment]
It's too much churn. I realize everyone is approving this, but I do not want to maintain it. Closing.

**Pull request closed without merging**
