### PR TITLE
Change license to GPL2/LGPL3

### PR DESCRIPTION
**Pull request by obnoxxx**
Signed-off-by: Michael Adam <obnox@redhat.com>
Signed-off-by: Luis Pabón <lpabon@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
@centos-ci test this please

**Comment by obnoxxx** [comment]
@centos-ci please test

**Comment by obnoxxx** [comment]
how on earth do I get @centos-ci to test this, please?

**Comment by lpabon** [comment]
ok to test @centos-ci

**Comment by obnoxxx** [comment]
closing because it will be re-done slightly differently

**Pull request closed without merging**
