### PR TITLE
Fixed migration logic for replica < 3 volumes

### LINKED ISSUE #1628: cannot remove device with bricks
### Kind of issue
Bug

### Observed behavior
I run glusterfs with heketi in kubernetes.  I need to free up a device which already has some bricks in it.

what I wanted to do:
- disable device
- remove device
- delete device

on remove I get following error:
```
Error: Failed to remove device, error: Cannot replace brick 536681db039f498cda08173b85f2103d as only 1 of 2 required peer bricks are online
command terminated with exit code 255
```

### Expected/desired behavior
After setting device offline the bricks should be replicated to another enabled device. I have enough devices with free space on other nodes, so there should be no problem moving the bricks.

### Details on how to reproduce (minimal and precise)
- having 3 nodes with to devices each
- create glusterfs pvc with 2 replicas
- disable device where are bricks on
- remove the disabled device

### Information about the environment:

- Heketi version used (heketi-cli v9.0.0): 
- Operating system used:  centos 7, kubernetes 1.14
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):  gk-deploy

### Other useful information
I added some nodes manually via heketi after initial setup with topology file.

### PR DESCRIPTION
**Pull request by olivergregorius**
Fixed logic for enabling brick migration for volumes with replica < 3, at least 1 brick must be online as source for migration

### What does this PR achieve? Why do we need it?
Migrating bricks of replica 2 volumes failed because at least 2 bricks needed to be online. The PR fixes this issue ensuring that for replica < 3 volumes at least 1 brick must be online.

### Does this PR fix issues?

Fixes #1628

### CODE REVIEW

**Comment by olivergregorius** [comment]
CentOS mirror seems to be down/have changed. Please check and retrigger build and test.

**Comment by phlogistonjohn** [comment]
Travis tests are also failing, and these appear to be true test failures brought on by the changes. I suggest looking into these failures and pushing an update to the PR to fix them. This will also trigger a new run of the centos ci.

**Comment by olivergregorius** [comment]
After fixing the tests and retriggering jobs the Travis job passed. The Jenkins build job still fails with the CentOS mirror returning 404.

**Comment by phlogistonjohn** [comment]
@nixpanic any known issues in centos ci land? I am not sure why the scl stuff we need to run vagrant is suddenly failing.

**Comment by phlogistonjohn** [comment]
@olivergregorius please drop or squash the last two commits (and force push) so that those extraneous changes don't become part of history. If you're not sure how to do that just ask and I'll try to provide more detailed steps.

**Comment by phlogistonjohn** [comment]
Change to the test for replica = 2 looks OK to me.

**Comment by phlogistonjohn** [comment]
retest this please

**Comment by raghavendra-talur** [comment]
The changes look good to me. 

Using 1 of 2 bricks as source for data migration is risky but I am convinced that it is only as risky as creating a replica 2 volume.

**Comment by phlogistonjohn** [comment]
> The changes look good to me.
> 
> Using 1 of 2 bricks as source for data migration is risky but I am convinced that it is only as risky as creating a replica 2 volume.

I concur. Once the patch history has been cleaned up I will be OK to merge.

**Comment by phlogistonjohn** [comment]
Ping @olivergregorius  can you please clean up your commit history? I'd love to merge this.

**Comment by sbias** [comment]
Can this get merged please? This is just blocking me from replacing a device that is failing soon :(

**Comment by sbias** [comment]
Even this is blocking me right now and i just posted a comment to prefer to merge this, we might consider to read the comment of Raghavendra Talur in commit https://github.com/heketi/heketi/commit/5ab8f537fb0ebb4a3853c5ab51e0ea9cf333afd3

"Choosing data safety over migration features." is a very good point there. Maybe this should be an option so the user can choose if he want to go unsafe - something like --ignore-quorum-check

**Comment by raghavendra-talur** [comment]
@sbias Thanks for the contribution! We will look at the option(--ignore-quorum-check) you mentioned only if required.

**Comment by raghavendra-talur** [comment]
@olivergregorius Thanks for the contribution!

**Comment by amgads** [comment]
Where do I get the tar file with the fix?

**Comment by amgads** [comment]
Built the latest from master branch and still fails
2019-11-11 19:50:25 : ERROR : Command (/usr/bin/heketi-cli device remove 24fc82c9bf1b99f7ed34a75f158ba3cd) failed: (Error: Failed to remove device, error: Cannot replace brick e5258aad22c3963a4ec4418b4d77dfe3 as only 1 of 2 required peer bricks are online

**Comment by amgads** [comment]
is there any flag to use like "--ignore-quorum-check" in addition to the heketi-cli device remove <id>?

**Pull request merged**
