### PR TITLE
Rework allocator code to get rid of mock allocator and don't modify the allocator outside the loading function.

### PR DESCRIPTION
**Pull request by obnoxxx**
The mock allocator was only there still in the test code, because the test code was looking into the allocator, using its implementation.

This patchset introduces nwe methods HasDevice and HasNode to the allocator interface and changes the test code to use those. It then changes the test code to use the standard allocator instead of the mock one manually.

The mock allocator is unused now and can be removed.

### CODE REVIEW

**Comment by obnoxxx** [comment]
Adding "do not merge" label because there's still this one TODO commit.

**Comment by raghavendra-talur** [comment]
@obnoxxx Having looked at the existing code and the work required to add Node information to MockAllocator, I don't think we need to have MockAllocator.

The ring allocator is deterministic, hence can be used for all mocking purposes.

**Comment by obnoxxx** [comment]
Updated to remove the mock allocator.

**Comment by obnoxxx** [comment]
Also todo is now gone.

**Comment by obnoxxx** [comment]
Added some more cleanups. Now AddCluster and AddDevice are only called in NewSimpleAllocatorFromDb.

**Pull request merged**
