### PR TITLE
TSP should be backup-volfile server

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
As any node in the TSP can give the volifile for the client.

closes: #825 

Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
@heketi/maintainers Can you please review?

**Comment by obnoxxx** [comment]
@MohamedAshiqrh The patch looks clean to me, but if that can be done just like this, we need a unit test. :-)

**Comment by obnoxxx** [comment]
@centos-ci ok to test

**Comment by lpabon** [comment]
@MohamedAshiqrh 

I can see that it could work on line: https://github.com/heketi/heketi/blob/master/apps/glusterfs/volume_entry_create.go#L56 because volfiles can be taken from any host, but I'm not sure this would work on line: https://github.com/heketi/heketi/blob/master/apps/glusterfs/volume_entry_create.go#L52 ?

Maybe we can create a volfiles variable and a host one for mounting the volume? Does it matter? Is GlusterFS efficient enough to mount from one node which does not have the bricks, and be as fast as mounting from the node that does? Is mounting just getting the volfile, the the FUSE client actually reconnects to the actual node with the bricks?

**Comment by lpabon** [comment]
retest this please

**Comment by MohamedAshiqrh** [comment]
@lpabon Yes, It is getting the volfile and then mounting using the volfile. Volfile can be passed from any of the gluster node which belongs to the TSP. While mounting it will use the volfile to connect to (all) bricks doesn't matter which ip is mentioned to mount.

**Comment by MohamedAshiqrh** [comment]
@obnoxxx @lpabon added the unit test.

**Comment by obnoxxx** [comment]
@lpabon right, to make it even more clear, this is how the mount happens:  the mount proces just goes to some glusterd in the cluster. From this retrieves the volume information (volfile), in particular the brick server IPs, and then in the next step it opens connections to the brick servers. So the mount can be initiated to ANY node in the cluster.

Hence the mount can specify any ip of a gluster cluster node (tsp node).

**Comment by obnoxxx** [comment]
Maybe we could make it more clear by not calling the one MointPoint and the other backup-volfile-servers, but maybe calling the backup-volfile-servers backup-mount-ips or so... (in a separate patch)

**Comment by obnoxxx** [comment]
The patch LGTM.

**Comment by lpabon** [comment]
LGTM

**Pull request merged**
