### PR TITLE
Cli print root usage

### LINKED ISSUE #415: heketi-cli should display help, when invoked
heketi-cli should at least display help, when invoked.

Presently, you get nothing in the o/p, should give usage/help.

```
[root@dhcp42-41 ~]# heketi-cli 
[root@dhcp42-41 ~]#
```

### PR DESCRIPTION
**Pull request by obnoxxx**
This is a variant of @MohamedAshiqrh 's patch. for issue #410 . For me, it works as expected with and without the server var set.

Closes #415

### CODE REVIEW

**Comment by obnoxxx** [comment]
Not entirely sure that checking os.Args[1:] to prevent the "Server must be provided" message when calling heketi-cli without arguments is the best solution, but it works for me (TM). :-)

**Comment by MohamedAshiqrh** [comment]
@lpabon I have verified this patch for other commands. It looks good to me. I would recommend to take this patch in until we have a better way of dealing the problem. nice work @obnoxxx, I never thought it this way :-).

**Comment by lpabon** [comment]
Closes #415

**Comment by lpabon** [comment]
ok to test @centos-ci

**Comment by lpabon** [comment]
:+1: Tested

Actual output:

```
$ ./heketi-cli 
Usage:
  heketi-cli [flags]
  heketi-cli [command]

Examples:
  $ export HEKETI_CLI_SERVER=http://localhost:8080
  $ heketi-cli volume list

Available Commands:
  cluster                        Heketi cluster management
  device                         Heketi device management
  node                           Heketi Node Management
  setup-openshift-heketi-storage Setup OpenShift/Kubernetes persistent storage for Heketi
  topology                       Heketi Topology Management
  volume                         Heketi Volume Management

Flags:
  -h, --help                           help for heketi-cli
      --json                           
        Print response as JSON
      --log-flush-frequency duration   Maximum number of seconds between log flushes (default 5s)
      --secret string                  
        Secret key for specified user.  Can also be
        set using the environment variable HEKETI_CLI_KEY
  -s, --server string                  
        Heketi server. Can also be set using the
        environment variable HEKETI_CLI_SERVER
      --user string                    
        Heketi user.  Can also be set using the
        environment variable HEKETI_CLI_USER
  -v, --version                        
        Print version

Use "heketi-cli [command] --help" for more information about a command.
```

**Pull request merged**
