### PR TITLE
Add an option to customize the gluster-block prealloc default

### LINKED ISSUE #1501: Heketi should support disabling preallocation in gluster-block volumes
### Kind of issue

Feature request

### Observed behavior

For very large block volumes, preallocation can take a large enough time the gluster-block commands fail. Disabling preallocation would allow the creation to occur quickly at the cost of the blocks being allocated when the user first requests them (in the data path).

Currently heketi hard-codes the command line parameters "prealloc full" when a block volume is being created.

### Expected/desired behavior

We need to choose a mechanism to allow block volumes to be created with "prealloc no".

A short list of possible mechanisms that we can discuss:
* New element in block creation API
* Config file param/ environment variable
* Volume level "user.heketi.blahblah" option to cause all block volumes on a BHV to be thinly allocated.

### PR DESCRIPTION
**Pull request by phlogistonjohn**
### What does this PR achieve? Why do we need it?

Add a config file option and environment variable that can change the default value for the prealloc option given to gluster-block create when creating block volumes.

Fixes #1501

### Notes for the reviewer

The added test lightly abuse the fact that the "TestErrorHandling" suite can control the heketi process and configuration on a per-test basis. This isn't really an error handling test but it would have been too much to either rename the whole suite or create a new one!

### CODE REVIEW

**Comment by obnoxxx** [comment]
Looks great from a first glance. Will do thorough review once tests are available.

**Comment by raghavendra-talur** [comment]
> What is the reason to have a regex match instead of enums for prealloc?

@phlogistonjohn replied to me in a call that it is make upgrades/addition of more modes easy later. That is a valid use-case.

**Comment by obnoxxx** [comment]
Now that the lsof-logging patch #1483 is merged, this needs conflict resolution in rebase.

**Comment by obnoxxx** [comment]
ping

**Comment by phlogistonjohn** [comment]
Rebas'd

**Comment by obnoxxx** [comment]
```
09:59:41 --- FAIL: TestCleanupAfterRestart (60.25s)
09:59:41     assert.go:44: 
09:59:41         
ASSERT:	func (github.com/heketi/heketi/tests/functional/TestErrorHandling/tests.TestCleanupAfterRestart) 0x1345313
09:59:41         
	File /root/go/src/github.com/heketi/heketi/tests/functional/TestErrorHandling/tests/background_cleanup_test.go:99
09:59:41         
	Info: [expected info.InFlight == 0, got: 1]
```

Flaky? Maybe we need to wait for longer than 5 seconds...

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
```
13:07:46 --- FAIL: TestCreateClusterTLSNoVerify (0.40s)
13:07:46     assert.go:44: 
13:07:46         
ASSERT:	func (github.com/heketi/heketi/tests/functional/TestEnabledTLS/client_tls_test_test.testClientActions) 0x69b4ab
13:07:46         
	File /root/go/src/github.com/heketi/heketi/tests/functional/TestEnabledTLS/client_tls_test/client_tls_test.go:95
13:07:46         
	Info: [expected err == nil, got: Post https://localhost:8080/clusters: dial tcp [::1]:8080: connect: connection refused]
13:07:46 === RUN   TestClientFailUnknownAuthority
```
looks unrelated...

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
some network problem internally?
```
17:38:00 === RUN   TestVolumeNotDeletedWhenNodeIsDown
17:38:00 [negroni] Started GET /clusters
17:38:00 [negroni] Completed 200 OK in 250.053µs
17:38:00 [negroni] Started POST /clusters
17:38:00 [negroni] Completed 201 Created in 1.40392ms
17:38:00 [negroni] Started POST /nodes
17:38:00 [cmdexec] INFO 2019/01/31 17:38:00 Check Glusterd service status in node 192.168.10.100
17:38:03 [cmdexec] WARNING 2019/01/31 17:38:03 Failed to create SSH connection to 192.168.10.100:22: dial tcp 192.168.10.100:22: connect: no route to host
17:38:03 [negroni] Completed 400 Bad Request in 3.006631443s
17:38:03 [cmdexec] ERROR 2019/01/31 17:38:03 heketi/executors/cmdexec/peer.go:81:cmdexec.(*CmdExecutor).GlusterdCheck: dial tcp 192.168.10.100:22: connect: no route to host
17:38:03 [heketi] ERROR 2019/01/31 17:38:03 heketi/apps/glusterfs/app_node.go:107:glusterfs.(*App).NodeAdd: dial tcp 192.168.10.100:22: connect: no route to host
17:38:03 [heketi] ERROR 2019/01/31 17:38:03 heketi/apps/glusterfs/app_node.go:108:glusterfs.(*App).NodeAdd: New Node doesn't have glusterd running
17:38:03 [test] ERROR 2019/01/31 17:38:03 heketi/tests/functional/TestVolumeNotDeletedWhenNodeIsDown/tests/heketi_test.go:99:tests.setupCluster.func1: New Node doesn't have glusterd running
17:38:03 --- FAIL: TestVolumeNotDeletedWhenNodeIsDown (3.01s)
17:38:03     assert.go:44: 
17:38:03         
ASSERT:	func (github.com/heketi/heketi/tests/functional/TestVolumeNotDeletedWhenNodeIsDown/tests.setupCluster) 0x6c091f
17:38:03         
	File /root/go/src/github.com/heketi/heketi/tests/functional/TestVolumeNotDeletedWhenNodeIsDown/tests/heketi_test.go:127
17:38:03         
	Info: [expected err == nil, got: New Node doesn't have glusterd running]
17:38:03 FAIL
17:38:03 exit status 1
17:38:03 FAIL	github.com/heketi/heketi/tests/functional/TestVolumeNotDeletedWhenNodeIsDown/tests	3.020s
```

**Comment by obnoxxx** [comment]
retest this please

**Pull request merged**
