### PR TITLE
Update to OpenShift Origin 1.2.0

### LINKED ISSUE #399: Resync dependencies with OpenShift Origin release 1.2.0
This will make sure we obtain any fixes to libraries used to communicate with Kubernetes.

### PR DESCRIPTION
**Pull request by lpabon**
To update to OpenShift Origin, first, we needed to go into
the openshift/origin directory and do a godep restore.  That failed
because the commit hash godep has for k8s.io/kubernetes is *not*
for github.com/kubernetes/kubernetes, but instead for
github.com/openshift/kubernetes.  You must first create the
k8s.io/kubernetes from github.com/openshift/kubernetes, and only
then can you run godep restore from openshift/origin.

This meant that Heketi cannot use glock, since glock would pull
k8s.io/kubernetes from kubernetes/kubernetes and not find the
hash.  Because of this reason, we need to use godep instead
as kubernetes, openshift, etcd, and others use.

Closes #399 

Signed-off-by: Luis Pabón <lpabon@redhat.com>

### CODE REVIEW

**Comment by lpabon** [comment]
Automated functional tests pass

**Comment by lpabon** [comment]
More info: https://github.com/openshift/origin/issues/9546

**Comment by lpabon** [comment]
@heketi/dev @heketi/qe Note this change

**Comment by nixpanic** [comment]
Manually re-run the automated test in the CentOS CI after replacing `glock`
with `godep`. The test failed after ~30 minutes. It seems that at least one
dependency is not available. Could that be a problem introduced with this PR?

From https://ci.centos.org/view/Gluster/job/gluster_heketi-functional/11/console:
```
Heketi v2.0.2-dev-20-g46401df-pr_400
[heketi] INFO 2016/06/25 10:13:29 Loaded ssh executor
[heketi] INFO 2016/06/25 10:13:29 Loaded simple allocator
[heketi] INFO 2016/06/25 10:13:29 GlusterFS Application Loaded
Authorization loaded
Listening on port 8080

# github.com/heketi/heketi/tests/functional/TestVolumeSnapshotBehavior/tests
package github.com/heketi/heketi/tests/functional/TestVolumeSnapshotBehavior/tests (test)
	imports github.com/heketi/heketi/client/api/go-client
	imports github.com/dgrijalva/jwt-go: cannot find package "github.com/dgrijalva/jwt-go" in any of:
	/usr/local/go/src/github.com/dgrijalva/jwt-go (from $GOROOT)
	/root/go/src/github.com/dgrijalva/jwt-go (from $GOPATH)
FAIL	github.com/heketi/heketi/tests/functional/TestVolumeSnapshotBehavior/tests [setup failed]
Shutting down...
[heketi] INFO 2016/06/25 10:13:31 Closed

==> storage3: Removing domain...
==> storage2: Removing domain...

==> storage1: Removing domain...
==> storage0: Removing domain...
==> FAILED TestVolumeSnapshotBehavior
```

**Comment by lpabon** [comment]
@nixpanic thanks for trying it out.  The issue should be fixed now.

**Comment by lpabon** [comment]
Functional tests successful: https://ci.centos.org/view/Gluster/job/gluster_heketi-functional/13/

**Pull request merged**
