### PR TITLE
Add information to device metrics

### PR DESCRIPTION
**Pull request by phunx**
This commit adds several information elements to device metrics:
* Node Manage Hostname    `manage` (as a replacement of `hostname`)
* Node Storage Hostname    `storage`
* Device Id                            `id`
* Device PV UUID                 `pv_uuid`

Metrics tests have been also altered to reflect this change.

Signed-off-by: Justin Ferrieu <jferrieu@objectif-libre.com>

### What does this PR achieve? Why do we need it?

This PR adds more information to existing heketi device metrics. We could need these so we can make easier join queries with i.e. the gluster exporter metrics that could be useful for later use, dashboard making, etc.

Also these changes reflect more what we can see on the `topology info` of the heketi cli.

### CODE REVIEW

**Comment by phunx** [comment]
Thanks for the review, I have applied your recommendations in my last commit.

**Comment by phlogistonjohn** [comment]
The code itself looks good to me. We do, however, like a clean linear history in this project. Can you please squash your changes together? If you do so I will probably merge it. Thanks.

**Comment by wtownse** [comment]
Working on that now.  Sorry about that.

Wayne Townsend
Senior Engineer, Solutions Architecture
Dell EMC | Converged Platforms and Solutions Division
Office +1 919 406 0542
wayne.townsend@dell.com<mailto:wayne.townsend@dell.com>

**Comment by phlogistonjohn** [comment]
@wtownse  you haven't been involved in this PR up to this point. Are you commenting on the right PR/issue?

**Comment by wtownse** [comment]
I believe so that was the one I found mentioning the issue we have.
https://github.com/heketi/heketi/issues/1012

Please let me know if there is a different one I should reference.

Wayne Townsend
Senior Engineer, Solutions Architecture
Dell EMC | Converged Platforms and Solutions Division
Office +1 919 406 0542
wayne.townsend@dell.com<mailto:wayne.townsend@dell.com>

**Comment by phlogistonjohn** [comment]
@raghavendra-talur PTAL

**Pull request merged**
