### PR TITLE
Allow LogError to return an error from the supplied format string.

### LINKED ISSUE #491: Create a logger which acts like fmt.Errorf
What we would like to see is a logging function which would not just log the current error, but also return it.  It is similar to logger.Err(error), with the exception, that it takes string formatting.

### PR DESCRIPTION
**Pull request by jarrpa**
Closes #491

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
@jarrpa I'm confused: why 2 pull requests (this and #493) with an identical patch? Just by accident?

**Comment by jarrpa** [comment]
This one is wrong, it contains a typo.

**Comment by obnoxxx** [comment]
@jarrpa Ah!. Hint: you could have pushed over this branche and that would have updated this pull request. No need to close and create a new one.

**Comment by lpabon** [comment]
@jarrpa Yes, please create new branches for pull requests.

**Comment by obnoxxx** [comment]
@lpabon Oh, just to make sure I don't mistunderstand: I was suggesting that @jarrpa pushes over the same branche when updating a pull request instead of creating a new pull request (possibly by creating a new branch for each revision of the patch).

**Comment by lpabon** [comment]
@obnoxxx @jarrpa Ah, I see.  As long as it is not merged, that is definitely the process.

**Pull request closed without merging**
