### PR TITLE
set sudovar if its a non root user and execute gluster commands.

### PR DESCRIPTION
**Pull request by humblec**
If its root user dont set the sudovar.

### CODE REVIEW

**Comment by humblec** [comment]
@lpabon can you please review/merge this asap?

**Comment by lpabon** [comment]
@humblec Hi humble.  I get notified by email and Github when new pull requests are given.  If I do not provide a comment for more than a 5 days, then please ping me.

I have reviewed this fix on Friday, but I did not commit because we need to be really careful when editing the code which handles communication with the servers.  One of the main things I noticed is that sudo is still in one of the commands because it is past a `|`.  This would cause issues on systems without sudo.

Because we are so close to release and the code is not waiting for `sudo` fix, I would like instead to postpone in to Release 3.

This fix does provide two fixes.  One is the `sudo` fix, the other was better SSH failure strings.  Please make a new patch just to get the SSH failure strings, and we will fix `sudo` after Release 2.

**Comment by humblec** [comment]
@lpabon  
>This fix does provide two fixes. One is the sudo fix, the other was better SSH failure strings. Please make a new patch just to get the SSH failure strings, and we will fix sudo after Release 2.
>
iic, you are referring the GLOCKFILE change with 'better SSH failure strings'. Please confirm, so that I can create a PR with only that change.

**Comment by lpabon** [comment]
We will revisit this in Release 3.  The package utils is now part of Heketi as of #366 .

**Comment by lpabon** [comment]
No longer needed

**Pull request closed without merging**
