### PR TITLE
Doc improvements

### PR DESCRIPTION
**Pull request by obnoxxx**
Polish the heketi-cli manpage a bit.
As preparation for further commits.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Oh and of course the centos-ci failure has nothing to do with these manpage changes! :-)

**Comment by obnoxxx** [comment]
rebased on PR #966 which has been merged and touched the manpage

**Comment by obnoxxx** [comment]
rebased on latest master

**Comment by obnoxxx** [comment]
thanks!

**Pull request merged**
