### PR TITLE
fix incorrect indentation in example heketi.json

### PR DESCRIPTION
**Pull request by aioue**
### What does this PR achieve? Why do we need it?
Minor formatting

### Does this PR fix issues?

No

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Change looks good but could you please improve the commit message? Something like "fix incorrect indentation in example heketi.json" or something like that. Thanks.

**Comment by phlogistonjohn** [comment]
Can you please respond to the feedback provided? Otherwise, I may have to close this PR w/o taking this fix.

**Comment by raghavendra-talur** [comment]
I tried to edit the commit message as a maintainer. Looks like I can edit the PR title, make more commits to the branch but not edit the commit that already exists.

**Comment by phlogistonjohn** [comment]
As the original contributor was non-responsive to feedback about the commit message formatting, and the issue has lingered in the open state for many months, I am going to close it. It can always be reopened if needed.

**Pull request closed without merging**
