### PR TITLE
Some further cleanups after introduction of CmdExec

### PR DESCRIPTION
**Pull request by obnoxxx**
Remove some outdated references to sshexec and refactor the common config from sshexec into cmdexec.

### CODE REVIEW

**Comment by obnoxxx** [comment]
This is based on PR #974 .

**Comment by obnoxxx** [comment]
@raghavendra-talur, what do you think about @phlogistonjohn 's point?

> I intentionally didn't change the logger prefix in my series because I wanted to discuss that change and then forgot. My primary concern was if anyone had built tooling or tests around scraping the logs. For both kubernetes and ssh executors it always reported as 'sshexec'
> 
> If its not a major concern I'm happy with the rest of these changes - but I figured the first was worth thinking about.

Do we care about keeping the logging tag as "sshexec" even if it's inconsistent, or do we want to change it for consisteny?

**Comment by raghavendra-talur** [comment]
@obnoxXx I agree with the changes done. It was confusing to see sshexec in kubernetes environments. Some tooling update might be required at user's end but it would be worth it.

**Comment by phlogistonjohn** [comment]
Good enough for me. We'll take it.

**Pull request merged**
