### PR TITLE
travis: try to let the travis run pass again

### PR DESCRIPTION
**Pull request by obnoxxx**
Condense the coverage vs no-coverage test runs into
one if-else statement.

Signed-off-by: Michael Adam <obnox@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
an attempt...

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
@phlogistonjohn ok, now I see that what I thought needs fixing does not need fixing at all. Did I just misread the test output? We should really stop the test immediately when something fails, and clearly print out what failed...

**Comment by obnoxxx** [comment]
(This patch might still make the output less misleading...)

**Comment by phlogistonjohn** [comment]
> @phlogistonjohn ok, now I see that what I thought needs fixing does not need fixing at all. Did I just misread the test output? 

Possibly. It is kind of buried amongst other stuff (see below)

> We should really stop the test immediately when something fails, 

I somewhat agree and when I run tests manually I am almost always using the -x switch which I added to the top level runner to stop the tests on first failure. However, when the tests are run asynchronously (like thru travis) it makes sense to run the entire suite of tests and then print out all the different failures in case you hit multiple issues.

> and clearly print out what failed...

I strongly agree. The problem here was that the failure in pr #1003 is printed in between two travis commands (at the end of) make test and before make release. The make release command generates a lot of output and so you have to scroll back quite a bit to see the make test failures.

There's a couple things we could do. We could change the ordering of the commands so that make release comes before make test. We could also change the output of the test runner script so that it is bigger/bolder/more obvious (more colorful?). 


All that said I do like your change. Unless you or someone else NAKs it I'll probably merge it later.

**Pull request merged**
