### PR TITLE
Fix issues found during goimport

### PR DESCRIPTION
**Pull request by Madhu-1**
### What does this PR achieve? Why do we need it?
Fix issues found in when I ran the `goimport` tool

Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
the change to app_test.go was done by goimport tool, goimport does formatting also, do you want it in separate commit?

**Comment by phlogistonjohn** [comment]
> the change to app_test.go was done by goimport tool, goimport does formatting also, do you want it in separate commit?

Unless it's really difficult, yes please.

**Comment by Madhu-1** [comment]
@phlogistonjohn `gofmt` was complaining about the formatting done by `goimport` tool.
reverted back the formatting changes. PTAL.

**Comment by Madhu-1** [comment]
@obnoxxx below is my observation for not adding goimport tests

* This is the formatting done by `goimport`
```
goimports -d -e -w  apps/glusterfs/app_test.go 
diff -u apps/glusterfs/app_test.go.orig apps/glusterfs/app_test.go
--- apps/glusterfs/app_test.go.orig	2018-11-16 14:17:51.508389726 +0530
+++ apps/glusterfs/app_test.go	2018-11-16 14:17:51.508389726 +0530
@@ -180,9 +180,9 @@
 	defer os.Unsetenv("HEKETI_DB_PATH")
 
 	conf := &GlusterFSConfig{
-		Executor:  "crazyexec",
-		Allocator: "simple",
-		DBfile:    "/path/to/nonexistent/heketi.db",
+		Executor:                  "crazyexec",
+		Allocator:                 "simple",
+		DBfile:                    "/path/to/nonexistent/heketi.db",
 		CreateBlockHostingVolumes: true,
 		BlockHostingVolumeSize:    500,
 	}
```
* but gofmt is complaining about this formatting
```
$ ./tests/020-gofmt.sh 
nonstandard formatting: ./apps/glusterfs/app_test.go
```

**Comment by obnoxxx** [comment]
@Madhu-1 I don't see the connection with the struct formatting, since this PR only changes import orders?

Secondly, if gofmt already complains, why does the test not fail?
Do we need to adapt the gofmt test to be more strict?

**Comment by Madhu-1** [comment]
@obnoxxx `goimport` also does the formatting, but I have added changes related to import not for formatting, 
so because of this `gofmt` is not complaining.

**Comment by Madhu-1** [comment]
@obnoxxx ping, anything pending here?

**Comment by Madhu-1** [comment]
@obnoxxx added shell check for goimport PTAL

**Comment by Madhu-1** [comment]
@phlogistonjohn PTAL

**Comment by phlogistonjohn** [comment]
LGTM, let's also make sure goimports tool is available on our travis setup.
@obnoxxx still has a NACK on this atm, so we'll want his feedback as well.

**Comment by obnoxxx** [comment]
ok to test

**Comment by obnoxxx** [comment]
retest this please

(network error in the travis env it seems...)

**Pull request merged**
