### PR TITLE
go-client: disable KeepAlives

### PR DESCRIPTION
**Pull request by ateleshev**
### What does this PR achieve? Why do we need it?
This PR fixed connection leak in heketi go-client (TLS enabled)

You can see same problem requested to the golang repository:
https://github.com/golang/go/issues/24719#issuecomment-379371501

### Notes for the reviewer
heketi: 8.0.0
golang: 1.12.1

### Details
Our watcher requests to heketi one time per minute to get devices info. After one day works we have been seeing thousands  of established connections. We use TLS between our watcher and heketi server.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
@raghavendra-talur PTAL. I wonder if this option should be universally applied, given that we've also seen the client consume many sockets (fds) on non-HTTPS configurations.

**Comment by phlogistonjohn** [comment]
ok to test

**Comment by ateleshev** [comment]
HttpClient hasn't reused, that is why it make sense to disable KeepAlive globally.
@phlogistonjohn Can I update it for HTTP connections?

**Comment by phlogistonjohn** [comment]
I agree, and I think it's worth experimenting with. So go ahead and make the change and we'll see what it looks like.

**Comment by ateleshev** [comment]
@phlogistonjohn PTAL

**Comment by ateleshev** [comment]
@phlogistonjohn I have been testing reusing of http client with enabled KeepAlives, and it's works fine. It significantly decreased count of system calls. How do you think, is it make sense to do it in this PR?

**Comment by phlogistonjohn** [comment]
@ateleshev I wonder if it would make sense to have two (mutually exclusive) PRs, we'd have to pick one in the end, but at least we'd be able to see the test suite run with both options.
Also hoping @raghavendra-talur will provide some input because he's looked into this topic in the past.

**Comment by raghavendra-talur** [comment]
@ateleshev Thanks for the contribution!

There are two problems that we would like to solve
1. You are hitting problem 1 where you are see "seeing thousands of established connections" after one day of heketi client operations in a long running process.
2. We have seen many ports in TIME_WAIT state when many heketi client operations are performed rapidly(in different processes).

@phlogistonjohn and I ran some tests to compare the behavior of heketi-client with regards to port consumption/established connections.

The test case is

a. create 5 volumes
b. list the volumes 100 times

for i in {1..5}; do heketi-cli volume create --size=5 ; done
for i in {1..100}; do heketi-cli volume list ; done

The numbers we get are 
On the master branch: approximately 600
On #1298: approximately 100 
This PR: approximately 600

Therefore, we would like to see your version of reusing the client and KeepAlive enabled. If you would send the updated patch and if the numbers come close to 100, we would like to take your PR and make it part of release 9.

If you don't have time for it, please let us know and we will bring #1298 into a more merge-able state. Ideally, we would like to hear from you by 3rd April to make a decision.

**Comment by ateleshev** [comment]
@raghavendra-talur  I agree with you, my current realisation in this PR solve only first problem.
You may know, standard http package has some problems with closing of idle connections:
 - https://github.com/golang/go/issues/24739
I going to update this PR tomorrow. And we will discuss it

**Comment by ateleshev** [comment]
@raghavendra-talur PTAL

**Comment by phlogistonjohn** [comment]
The changes have suddenly got a lot more complicated looking to me. Although the bulk of the lines just appear to be `defer client.close()` type things. First off, I don't understand if the defers are required. How necessary are they?
Next, I am quite confused about the CloseIdler stuff which appears to be new in go1.12, right? If so that's worrysome to me because we a) need to support older versions of go (typically we want users to be able to compile on centos) b) don't even test on go 1.12 yet. Is this a case of older versions don't reap the benefits, but is still compatible? If so, what are those benefits?

Overall I liked the simplicity, if perhaps limited benefits of the early versions of the PR. However, I'm willing to be convinced of the benefits of this approach but I'm quite skittish to take the current form of the series for release 9. I'm not sure if you care about our release @ateleshev but I'm leaning toward just releasing without the client improvements but trying to get them squared away soon so they can be used in master for a while, any thoughts @raghavendra-talur ?

**Comment by raghavendra-talur** [comment]
@ateleshev Thanks for the links which explain the problem with http library in golang.

@phlogistonjohn @ateleshev I did a quick test on the latest PR using the same test as before. 


go version

```
$ go version
go version go1.11.5 linux/amd64
```

test case
```
a. create 5 volumes
b. list the volumes 100 times
```

The number of connections is approximately 100, which is same as in PR #1298 .

So functionally, we seem to be doing good with the latest update. I do agree with @phlogistonjohn that we need to do a few more things before merging the PR:

a. Write test case(s) to ensure we are not breaking anything
b. Understand the difference between MaxIdleConnsPerHost and CloseIdleConnections
c. Think about the implications of go version requirements.

@ateleshev If you are not waiting on release 9 to have this PR, then we can make the release without this PR and merge it after above tasks are done.

**Comment by ateleshev** [comment]
The PR https://github.com/heketi/heketi/pull/1298 does not solve problem with thousands of established connections
```
c.httpClient.Transport = &http.Transport{
    MaxIdleConnsPerHost: 0,
}
```
MaxIdleConnsPerHost = 0 it means - use default value from standard go http library.

https://golang.org/src/net/http/transport.go#L57
```
// DefaultMaxIdleConnsPerHost is the default value of Transport's
// MaxIdleConnsPerHost.
const DefaultMaxIdleConnsPerHost = 2
```

https://golang.org/src/net/http/transport.go#L730
```
func (t *Transport) maxIdleConnsPerHost() int {
	if v := t.MaxIdleConnsPerHost; v != 0 {
		return v
	}
	return DefaultMaxIdleConnsPerHost
}
```
As you can see, idle connections will not create if specified  MaxIdleConnsPerHost < 0 or DisableKeepAlives = false
https://golang.org/src/net/http/transport.go#L743
```
func (t *Transport) tryPutIdleConn(pconn *persistConn) error {
	if t.DisableKeepAlives || t.MaxIdleConnsPerHost < 0 {
		return errKeepAlivesDisabled
	}
```

There is two issues which affect http connections:
- https://github.com/golang/go/issues/24739
- https://github.com/golang/go/issues/24719

And you can read in this comment to issue:
https://github.com/golang/go/issues/24719#issuecomment-379371501
```
It does not happen with DefaultTransport, or calling CloseIdleConnections.
```

@phlogistonjohn @raghavendra-talur  I clearly understand, the release it is your responsibility, and you must decide which PR make sense to merge

**Comment by ateleshev** [comment]
@phlogistonjohn ```defer client.close()``` - it is solution which guaranteed close all open idle connections correctly before process exit (it needs only if connection use TLS), and it will work only for golang 1.12, in the previous versions of go KeepAlive will be disabled.

```CloseIdleConnections``` will be helpful with TLS certificates rotation in demonized applications.

**Comment by phlogistonjohn** [comment]
I'd love to see some improvement in this area but this PR has gone quite stale. If we could make some small incremental improvements in this area it would be much easier to review and less change to unknown risks to the current users.
If you're not interested in perusing this approach I understand but I think we'd need to close this PR. If I don't hear back in a couple of weeks I will close this out.

**Comment by ateleshev** [comment]
Hello @phlogistonjohn. I need some time to recheck this PR. Would you like to remove ```defer heketi.Close()```?

**Comment by phlogistonjohn** [comment]
To be honest I didn't expect you to respond so quickly so I am quite rusty on the technical aspects of the PR as well. 
I do remember that it started off as a smaller set of changes and I'd like to get back to that point (first) before doing large changes. Small things that make concrete incremental improvements will make things more reviewable and more likely to land in the code quickly. Anything that requires that callers change how access them are much more difficult because most of the code using heketi apis are old-ish and unlikely to change quickly if at all.
We'd also need more tests as @raghavendra-talur commented on Apr 4, 2019.

**Comment by ateleshev** [comment]
Okay, let's improve this step by step

**Comment by phlogistonjohn** [comment]
Unfortunately, we do not think we have the resources to properly review and integrate a change of this extent. I truly appreciate your efforts to improve heketi but I do not think it is reasonable to leave this PR open, lingering, any more.
Thanks again.

**Pull request closed without merging**
