### PR TITLE
Initial commit on cli with posix support

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by lpabon** [comment]
Looks like some of your files need to use gofmt

**Comment by lpabon** [comment]
Do we still need this PR?

**Comment by MohamedAshiqrh** [comment]
We do not need this anymore

**Comment by MohamedAshiqrh** [comment]
Closing this PR as we are going ahead with cobra(https://github.com/heketi/heketi/pull/282)

**Pull request closed without merging**
