### PR TITLE
Typo Error under help menu for heketi-cli

### PR DESCRIPTION
**Pull request by tchaphek**
Typo error for retrieve fixed inside the heketi-cli help

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
@tchaphek looks good to me.

**Comment by obnoxxx** [comment]
@tchaphek ping. would you be willing to address the requests? (i.e. fix the commit messages)?
If not, I can take care of that for you.

**Comment by tchaphek** [comment]
sure, michael, i'll change it.

**Comment by obnoxxx** [comment]
LGTM, thanks!

**Pull request merged**
