### PR TITLE
errInj: add error Injection tests for block expand

### PR DESCRIPTION
**Pull request by pkalever**
### What does this PR achieve? Why do we need it?

Test Summary:
*** PASS: TestBlockExpandInject (157.68s)
    *** PASS: TestBlockExpandInject/TryExpandSuccess (24.41s)
    *** PASS: TestBlockExpandInject/TryExpandFailAtVeryBeginning (24.01s)
    *** PASS: TestBlockExpandInject/TryExpandFail (25.31s)
    *** PASS: TestBlockExpandInject/RetryExpandFail (25.26s)
    *** PASS: TestBlockExpandInject/RetryExpandSuccessWithSameSize (24.83s)
    *** PASS: TestBlockExpandInject/RetryExpandSuccessWithDifferentSize (24.40s)

### Notes for the reviewer
Depends on: https://github.com/heketi/heketi/pull/1718, https://github.com/heketi/heketi/pull/1725

Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
@pkalever generally we include the changes we depend on in our PRs. Right now this can't even compile. Do you want to re-push with the patches from #1718 and #1725. Once those are merged you can rebase and they'll "disappear" from this pr.
Otherwise we have to wait for those to be merged before getting any test runs...

Either way I'm sticking a dnm tag on here for now.

**Comment by pkalever** [comment]
> @pkalever generally we include the changes we depend on in our PRs. Right now this can't even compile. Do you want to re-push with the patches from #1718 and #1725. Once those are merged you can rebase and they'll "disappear" from this pr.
> Otherwise we have to wait for those to be merged before getting any test runs...
> 
> Either way I'm sticking a dnm tag on here for now.

@phlogistonjohn you are right, I have confidence that both the PR that you pointed above will be merged shortly. And I thought we can just give '/ok retest' again. But if you think that is going to take some time, I'm ok to pile the other PR's here.

I don't like this part of GitHub actually, Gerrit manages it well.

**Comment by phlogistonjohn** [comment]
> > @pkalever generally we include the changes we depend on in our PRs. Right now this can't even compile. Do you want to re-push with the patches from #1718 and #1725. Once those are merged you can rebase and they'll "disappear" from this pr.
> > Otherwise we have to wait for those to be merged before getting any test runs...
> > Either way I'm sticking a dnm tag on here for now.
> 
> @phlogistonjohn you are right, I have confidence that both the PR that you pointed above will be merged shortly. And I thought we can just give '/ok retest' again. But if you think that is going to take some time, I'm ok to pile the other PR's here.

In the mean time, PR  #1724 has been merged and that should be sufficient for this PR. If you rebase #1718 (which needs a rebase/merge anyway ATM) on master and then rebase this PR on #1718s content we should be able to start testing both immediately.

> 
> I don't like this part of GitHub actually, Gerrit manages it well.

De gustibus non est disputandum. ;-)

**Comment by pkalever** [comment]
> In the mean time, PR #1724 has been merged and that should be sufficient for this PR. If you rebase #1718 (which needs a rebase/merge anyway ATM) on master and then rebase this PR on #1718s content we should be able to start testing both immediately.

Make sense, I will be on it shortly.
> 
> > I don't like this part of GitHub actually, Gerrit manages it well.
> 
> De gustibus non est disputandum. ;-)

:+1:

**Comment by pkalever** [comment]
FYI: Rebasing on PR#1718 done. Thanks!

**Comment by raghavendra-talur** [comment]
@pkalever May I request for one more test? Using errInj we provide  gluster-block info output that *does not* have the usable size field. To catch the kind of problems we will run into when the gluster container/gluster-block version is older than what heketi expects.

**Comment by phlogistonjohn** [comment]
ok to test

**Comment by pkalever** [comment]
> @pkalever May I request for one more test? Using errInj we provide gluster-block info output that _does not_ have the usable size field. To catch the kind of problems we will run into when the gluster container/gluster-block version is older than what heketi expects.


I get the point.

gluster-block info command doesn't maintain the usable-size, but in heketi code, we observe that from `RESIZE FAILED ON` field of `gluster-block info ...` output

```
[gluster-block info vol_c77732c9a51cd5942a67af583b050fa7/blockvol_1659001f43aa19e918cdda93cb1413e8 --json] on [192.168.121.55:22]: Stdout [{ "NAME": "blockvol_1659001f43aa19e918cdda93cb1413e8", "VOLUME": "vol_c77732c9a51cd5942a67af583b050fa7", "GBID": "f3140367-ea08-419c-b587-e558ac43cf90", "SIZE": "3.0 GiB", "HA": 3, "IOTIMEOUT": "0 Seconds", "PASSWORD": "", "EXPORTED ON": [ "192.168.121.55", "192.168.121.206", "192.168.121.253" ], "RESIZE FAILED ON": { "192.168.121.55": "2.0 GiB" } }]
```

That way, I understand that @raghavendra-talur was asking for a case where `gluster-block info ...` doesn't have `RESIZE FAILED ON` field. If I get that right, the answer is we already have one such check at `TestBlockExpandInject/TryExpandFailAtVeryBeginning` https://github.com/heketi/heketi/blob/1483c78355d0dd7ba364fda02138d7e811481d61/tests/functional/TestErrorHandling/tests/block_expand_test.go#L134


@raghavendra-talur please let me know if we need more such checks.

Thanks!

**Comment by raghavendra-talur** [comment]
> > @pkalever May I request for one more test? Using errInj we provide gluster-block info output that _does not_ have the usable size field. To catch the kind of problems we will run into when the gluster container/gluster-block version is older than what heketi expects.
> 
> I get the point.
> 
> gluster-block info command doesn't maintain the usable-size, but in heketi code, we observe that from `RESIZE FAILED ON` field of `gluster-block info ...` output
> 
> ```
> [gluster-block info vol_c77732c9a51cd5942a67af583b050fa7/blockvol_1659001f43aa19e918cdda93cb1413e8 --json] on [192.168.121.55:22]: Stdout [{ "NAME": "blockvol_1659001f43aa19e918cdda93cb1413e8", "VOLUME": "vol_c77732c9a51cd5942a67af583b050fa7", "GBID": "f3140367-ea08-419c-b587-e558ac43cf90", "SIZE": "3.0 GiB", "HA": 3, "IOTIMEOUT": "0 Seconds", "PASSWORD": "", "EXPORTED ON": [ "192.168.121.55", "192.168.121.206", "192.168.121.253" ], "RESIZE FAILED ON": { "192.168.121.55": "2.0 GiB" } }]
> ```
> 
> That way, I understand that @raghavendra-talur was asking for a case where `gluster-block info ...` doesn't have `RESIZE FAILED ON` field. If I get that right, the answer is we already have one such check at `TestBlockExpandInject/TryExpandFailAtVeryBeginning`
> 
> https://github.com/heketi/heketi/blob/1483c78355d0dd7ba364fda02138d7e811481d61/tests/functional/TestErrorHandling/tests/block_expand_test.go#L134
> 
> @raghavendra-talur please let me know if we need more such checks.
> 
> Thanks!

Yes, but in that test case the size and usableSize both remain at 1GiB. We need a test case where the size grows but the usable size remains the same. I think, with the logic in the other PR https://github.com/heketi/heketi/pull/1718/commits/3fa87a867a666bfe2d91e1f57ad167d039af865e#diff-cf715626e87849fee70acd92f30dcc35R136 on how what to return as usableSize we might have a bug where expansion can't be retried if:
1. gluster-block is older version that does not have the RESIZE FAILED ON field
2. expansion failed in the later part in gluster-block(i.e after the file was expanded)

**Comment by pkalever** [comment]
> Yes, but in that test case the size and usableSize both remain at 1GiB. We need a test case where the size grows but the usable size remains the same.

Sure, I can make a test for this case, thanks for the details @raghavendra-talur 

I think, with the logic in the other PR [3fa87a8#diff-cf715626e87849fee70acd92f30dcc35R136](https://github.com/heketi/heketi/commit/3fa87a867a666bfe2d91e1f57ad167d039af865e#diff-cf715626e87849fee70acd92f30dcc35R136) on how what to return as usableSize we might have a bug where expansion can't be retried if:
> 
> 1. gluster-block is older version that does not have the RESIZE FAILED ON field
> 2. expansion failed in the later part in gluster-block(i.e after the file was expanded)

There are two cases here:
If gluster-block is older version and expansion failed partially,
1. If that block volume was created with the newer version of heketi:
Then, code at 
https://github.com/heketi/heketi/blob/2e3b8202af71b48d8d38c27afcb442ecd32fe9d5/apps/glusterfs/operations_block_volume.go#L243

Will set the UsableSize=BlockVolumeSizeCreateReqSize already as part of Create's Finalize(), so the minimum usableSize will be that in the worst case.

2. If that block volume was created with the older version of heketi:
it will say UsableSize as 0

@raghavendra-talur this is working as expected (meaning as I desired), do you think that is a better way?

The only hack I can think of is, while doing upgrades, update the UsableSize=Size in the db for all block volumes.

Thoughts?

Thanks!

**Comment by raghavendra-talur** [comment]
> There are two cases here:
> If gluster-block is older version and expansion failed partially,
> 
> 1. If that block volume was created with the newer version of heketi:
>    Then, code at
>    https://github.com/heketi/heketi/blob/2e3b8202af71b48d8d38c27afcb442ecd32fe9d5/apps/glusterfs/operations_block_volume.go#L243
> 
> Will set the UsableSize=BlockVolumeSizeCreateReqSize already as part of Create's Finalize(), so the minimum usableSize will be that in the worst case.
Yes, we should tried to avoid this scenario.
> 
> 2. If that block volume was created with the older version of heketi:
>    it will say UsableSize as 0

This is good.
> 
> @raghavendra-talur this is working as expected (meaning as I desired), do you think that is a better way?
> 
> The only hack I can think of is, while doing upgrades, update the UsableSize=Size in the db for all block volumes.

Yes, @phlogistonjohn referred to this approach in one of the calls. You can use https://github.com/heketi/heketi/blob/36f4f8845ae9eee68345f88fa56107e7b4e7f926/apps/glusterfs/dbcommon.go#L234 as a reference.  IMO, it is good if we add it.

> 
> Thoughts?
> 
> Thanks!

**Comment by pkalever** [comment]
@raghavendra-talur please note the requested new test case addition is in-place now. Thanks!

**Comment by raghavendra-talur** [comment]
> > There are two cases here:
> > If gluster-block is older version and expansion failed partially,
> > 
> > 1. If that block volume was created with the newer version of heketi:
> >    Then, code at
> >    https://github.com/heketi/heketi/blob/2e3b8202af71b48d8d38c27afcb442ecd32fe9d5/apps/glusterfs/operations_block_volume.go#L243
> > 
> > Will set the UsableSize=BlockVolumeSizeCreateReqSize already as part of Create's Finalize(), so the minimum usableSize will be that in the worst case.
> 
> Yes, we should tried to avoid this scenario.
> 
> > 1. If that block volume was created with the older version of heketi:
> >    it will say UsableSize as 0
> 
> This is good.
> 
> > @raghavendra-talur this is working as expected (meaning as I desired), do you think that is a better way?
> > The only hack I can think of is, while doing upgrades, update the UsableSize=Size in the db for all block volumes.
> 
> Yes, @phlogistonjohn referred to this approach in one of the calls. You can use
> 
> https://github.com/heketi/heketi/blob/36f4f8845ae9eee68345f88fa56107e7b4e7f926/apps/glusterfs/dbcommon.go#L234
> 
> as a reference. IMO, it is good if we add it.
> > Thoughts?
> > Thanks!

These comments are invalid and no update to the db is required to fill in usableSize field.

**Pull request merged**
