### PR TITLE
Kube smoke test fixes

### PR DESCRIPTION
**Pull request by obnoxxx**
Combined work of Luis and myself.

### CODE REVIEW

**Comment by obnoxxx** [comment]
Replaces PR #589 .

**Comment by obnoxxx** [comment]
ok... it still fails in TesKubeSmokeTest:
'''
Step 6 : ADD ./heketi.json /etc/heketi/heketi.json
 ---> bea4f63dfab3
Removing intermediate container aa7b8d21df51
Step 7 : RUN mkdir /var/lib/heketi
 ---> Running in eab77b3fcb1f
permission denied
Container command could not be invoked.
==> ERROR: Unable to create docker container
==> FAILED TestKubeSmokeTest
==> TEARDOWN TestKubeSmokeTest
'''
This works locally for me.

**Comment by lpabon** [comment]
This works locally for me also.  I think we need to do a chmod on the image that is created so that we can copy it.

**Comment by obnoxxx** [comment]
@lpabon This is a different error. It happens inside the ```docker build``` command. I think what happens is that the ```mkdir /var/lib/heketi``` gets permission denied.

**Comment by obnoxxx** [comment]
I think we are getting further than before. This error shows that the actual setup of minikube has succeeded. I'm going to push these changes. and work on a new patch for this new issue.

**Pull request merged**
