### PR TITLE
Update k8s.io dependencies to v0.24.1

### PR DESCRIPTION
**Pull request by dims**
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### Does this PR fix issues?

Fixes #

### CODE REVIEW

**Comment by dims** [comment]
@phlogistonjohn @humblec can you please trigger the CI jobs?  i am hoping this change is enough to switch dependencies!

**Comment by humblec** [comment]
```06:08:03 fatal: --points-at option is only allowed with -l.
06:08:03 make[2]: Entering directory `/root/go/src/github.com/heketi/heketi'
06:08:03 go build  -ldflags "-X main.HEKETI_VERSION=v10.0.0-82-g5be0cfd-pr_1903 -extldflags '-z relro -z now'" -o heketi
06:08:03 # github.com/heketi/heketi/pkg/kubernetes
06:08:04 pkg/kubernetes/backupdb.go:92:26: not enough arguments in call to secrets.Create
06:08:04 	have (*"k8s.io/api/core/v1".Secret)
06:08:04 	want (context.Context, *"k8s.io/api/core/v1".Secret, "k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions)
06:08:04 make[2]: Leaving directory `/root/go/src/github.com/heketi/heketi'
06:08:04 make[2]: *** [heketi] Error 2```

**Comment by dims** [comment]
yep i mentioned this on slack :)

**Pull request closed without merging**
