### PR TITLE
Set the "group gluster-block" options when manually creating block-hosting volumes

### LINKED ISSUE #1226: volume create request with block flag does not set the block-specific volume options
### Kind of issue

Bug

### Observed behavior

`heketi-cli volume create --size=X --block` does not set the `group gluster-block` volume options.
(Corresponding for the API request.)

### Expected/desired behavior

The cli or api request with the block flag should set the volume options.

### Details on how to reproduce (minimal and precise)

Run `heketi-cli volume create --size=<X> --block`.

### Information about the environment:

- Heketi version used (master): 
- Operating system used: fedora
- Heketi compiled from sources, as a package (rpm/deb), or container: source 
- Using kubernetes, openshift, or direct install: local install with mock translator

### PR DESCRIPTION
**Pull request by obnoxxx**
Fixes #1226

### CODE REVIEW

**Comment by obnoxxx** [comment]
note: if you specify `group gluster-block` on the cmdline/in the request as well, this will have it listed twice. Should we make that unique?...

**Comment by nixpanic** [comment]
I think this fails when the block hosting volume does not have replication enabled (durability=none). See kubevirt/kubevirt-ansible#260 for some details. The set of options for gluster-block is [here](https://github.com/gluster/glusterfs/blob/master/extras/group-gluster-block).

**Comment by obnoxxx** [comment]
@nixpanic writes:
> I think this fails when the block hosting volume does not have replication enabled (durability=none). See kubevirt/kubevirt-ansible#260 for some details. The set of options for gluster-block is here.

Hmm, that's true, but actually unrelated to the fact that this setting is not applied when manually creating block-hosting volumes.

Group options should probably be made more intelligent in gluster... :-)
(or the options that do not apply should be made no-ops if not applicable, or at the very least we need different flavors of group options...)

**Comment by nixpanic** [comment]
On Fri, Jun 29, 2018 at 12:17:51AM -0700, Michael Adam wrote:
> 
> @phlogistonjohn writes:
> > @obnoxxx writes:
> > >  note: if you specify group gluster-block on the cmdline/in the
> > >  request as well, this will have it listed twice. Should we make
> > >  that unique?...
> > 
> > I think so. My preferred approach would to be to only set the group
> > to gluster-block if vol.Info.Block is true and there are no other
> > groups specified in the options list.
> 
> I kind of disagree: I don't think we should not set it at all. It
> should be up to gluster to resolve conflicts for various group
> options. They are not all mutually exclusive either. I propose to
> **prepend** the block option to the list of provided volume options in
> this patch, instead of **appending** it, so that user-provided options
> can take precedence? -- OK?

That makes sense to me.

**Comment by phlogistonjohn** [comment]
> I kind of disagree: I don't think we should not set it at all. It should be up to gluster to resolve conflicts for various group options. They are not all mutually exclusive either. I propose to prepend the block option to the list of provided volume options in this patch, instead of appending it, so that user-provided options can take precedence? -- OK?

If that's how gluster works, then OK. Do you need to make any other changes to the patches or do you want a re-review given the current consensus?

**Comment by obnoxxx** [comment]
> If that's how gluster works, then OK. Do you need to make any other changes to the patches or do you want a re-review given the current consensus?

Just the change to **prepend** instead of **append**. Will update shortly.

**Pull request merged**
