### PR TITLE
List and display pending ops through heketi api

### PR DESCRIPTION
**Pull request by phlogistonjohn**
### What does this PR achieve? Why do we need it?

The overall goal of this PR is to support the commands:
```
heketi-cli server operations list
```
and
```
heketi-cli server operations info $ID
```

It adds new types to the API, new endpoints, new client functions and new cli commands.

This work is part of the effort to implement clean up of operations (issue #1401). This PR supports that effort by allowing the users of heketi to list and display pending operations on a live server rather than dumping the db to json.

Due to some short-sighted naming on my part, the `server operations info` command now serves two purposes. If no ID is given it prints a short summary of all operations in the system. If it is given an ID then it prints a description of a specific pending operation.

### Does this PR fix issues?

Related to #1401.

### Notes for the reviewer

This PR is built on top of the changes in PR #1430. Please review that PR first. That PR is needed so that we can ask the tracker about particular pending operation IDs.

### CODE REVIEW

**Comment by obnoxxx** [comment]
@phlogistonjohn i rebased it for you

**Comment by obnoxxx** [comment]
retest this please

**Comment by phlogistonjohn** [comment]
retest this please

**Comment by phlogistonjohn** [comment]
retest this please

**Comment by phlogistonjohn** [comment]
retest this please

**Comment by obnoxxx** [comment]
centos-ci failure was the not fully deterministic throttling test...

**Pull request merged**
