### PR TITLE
github: Add a pull request template

### PR DESCRIPTION
**Pull request by obnoxxx**
Signed-off-by: Michael Adam <obnox@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
Note that the comment will not be shown in the PR any more, only when editing the PR description.
Maybe this is a little too much text in the comment. This could also go into the contributing guide, but I thought it might be nice to have it all in in front of you when writing a PR.

Happy to reduce it / move some of it to a doc if that's preferred.

**Comment by phlogistonjohn** [comment]
>Note that the comment will not be shown in the PR any more, only when editing the PR description.
Maybe this is a little too much text in the comment. This could also go into the contributing guide, but I thought it might be nice to have it all in in front of you when writing a PR.
>
>Happy to reduce it / move some of it to a doc if that's preferred.

Yeah, I feel that at this length its well into "TL;DR" territory. IMO what would be better is to convert it into a shorter bullet-point list and have the bullets (or items w/in the bullets) link to the contributing doc. 

So it might become something more of a quick checklist like:
```
* Does your PR encompass one development topic? [ref]
* Do your individual commits accomplish a single task? [ref]
* Do your commit messages describe the rationale for your change? [ref]
* Have you run 'make test'? [ref]
```
We could throw in a little more wording pre- and post-list but I find lists are more attention grabbing and keeping it short will increase the likelihood that it will be read.

I'd also argue that "thing" is too vague in this context but I'd rather wrangle that in a change to the contributing doc.

**Comment by obnoxxx** [comment]
This is kind of dependent on PR #1096 as it now contains links to sections that only exist in the PR.

**Comment by obnoxxx** [comment]
heh, this can't possibly have broken centos-ci ... ;-)

retest this please

**Comment by obnoxxx** [comment]
retest this please

**Pull request merged**
