### PR TITLE
Add TLS support for Heketi Server

### PR DESCRIPTION
**Pull request by rsevilla87**
Adding TLS support for Heketi Server. This functionality is crucial in some environments where all communications should be encrypted.

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
@rsevilla87 thanks for the PR. I have had a look and change looks good. I am taking time to read a little more on the docs. We will have review comments soon!

**Comment by phlogistonjohn** [comment]
Ideally, we'd want some tests for this feature but it's a small enough patch that looks straightforward to me.

**Comment by phlogistonjohn** [comment]
@centos-ci  ok to test

**Comment by rsevilla87** [comment]
@phlogistonjohn ping :)

**Comment by phlogistonjohn** [comment]
Hi @rsevilla87 we usually like to have two approvals before merging. I'll ping some other team members to get a 2nd review.

**Comment by raghavendra-talur** [comment]
This probably requires changes/updates in heketi client library for feature completion but the PR is complete as far as heketi server functionality is concerned.

**Comment by phlogistonjohn** [comment]
> There is no client code, so it is rather useless right now. And if the server enables TLS, the current client won't be able to connect any more - correct?

The default Go client will support HTTPS automatically. If the cert is signed by a CA the client knows about I don't think any additional code changes would be needed. However, to best use the client we probably want to make it easy to feed it options for skipping verification or feeding it a custom cert for verification.

>  There is not real test yet, of functionality through a TLS connection, just a test of being able to connect. (Of course this is kind of implied by no 1.)

Sure.

> The way to specify the certificate/key files is very static through the config file. Hence it's harder in a kubernetes environment to specify them. Could we make it overrideable by environment variables in apps/glusterfs/app.go (like for HEKETI_EXECUTOR and others)?

This seems OK for this PR. It would definitely make things more easier to set up w.r.t. adding new certs/keys to the heketi pod configuration.

> I would at least want to have client code alongside the server code. Otherwise this might make it into the release. Tests and config flexibility can be added later.

Personally, I had figured we'd do the client stuff in a follow up pr, but if you feel strongly enough about I'm willing to help add some of the needed configuration ability to the client apis.

**Comment by obnoxxx** [comment]
Thanks again for your contribution @rsevilla87 !

**Pull request merged**
