### PR TITLE
Update Release 3 to Release 3.1

### PR DESCRIPTION
**Pull request by lpabon**

### CODE REVIEW

**Comment by obnoxxx** [comment]
dang, again failed centos-ci:

```
[heketi] ERROR 2016/11/04 08:25:34 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry.go:429: Unable to delete volume vol_c59ec1934727f954440c23903325c70b because it contains 1 snapshots
[heketi] ERROR 2016/11/04 08:25:34 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:274: Failed to delete volume c59ec1934727f954440c23903325c70b: Unable to delete volume vol_c59ec1934727f954440c23903325c70b because it contains 1 snapshots
```

**Comment by obnoxxx** [comment]
Is that flakey?
@centos-ci retest  please

**Comment by lpabon** [comment]
FYI, the failure is in the minikube tests:

```
Secret is = 
==> ERROR: Secret is empty
==> FAILED testHeketiRpc.sh
```

**Comment by obnoxxx** [comment]
@lpabon where do you see that minikube error?

All I see when I navigate to the centos-ci and click on console output (https://ci.centos.org/job/gluster_heketi-functional/128/console) is the error i pasted above...

**Comment by obnoxxx** [comment]
ok, i see it in the plain text output https://ci.centos.org/job/gluster_heketi-functional/128/consoleText

but what does that error mean. how can we resolve that?

**Comment by obnoxxx** [comment]
Merged according to @lpabon 's recommendation to ignore this minikube error.

**Pull request merged**
