### PR TITLE
Clean up the utils package

### PR DESCRIPTION
**Pull request by phlogistonjohn**
### What does this PR achieve? Why do we need it?

Minor restructuring of the utils package to return the package to a assortment of simple utility functions.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
@obnoxxx @raghavendra-talur @andersla PTAL
Merging this will help me unwind my stack a bit. :-)

**Comment by obnoxxx** [comment]
@phlogistonjohn writes:
> @obnoxxx @raghavendra-talur @andersla PTAL

Sure you did not mean @ansiwen ? :-)

**Comment by phlogistonjohn** [comment]
I tried to change that twice! I don't why github changed it back on me, I swear.

**Comment by obnoxxx** [comment]
Trivial conflict resolution required. @phlogistonjohn

**Comment by obnoxxx** [comment]
what's the problem with centos-ci ?...

**Pull request merged**
