### PR TITLE
 api: support colon chars in device paths

### LINKED ISSUE #1246: Disk symlink not accepted by heketi
As the device names are not persistence across reboot, I was using symlink of the disk to configure Heketi topology. 

In my setup, both Heketi (version 5) and GlusterFS  (version 3.12.1) runs a Pods. symlink "/dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:1:0" was working perfectly for us. However, now we want to move to latest version of Heketi and it looks like Heketi does not accept this symlink as device configuration. Among all, this is the only symlink ("/dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:1:0") which is available for a raw disk.

I need your help/suggestion here.
 1) What alternative mechanism community is following to provide persistence name of a raw disk into Heketi Topology. 
 2) Ideally validation check is good, but can we skip the validation logic on the disk path

### PR DESCRIPTION
**Pull request by phlogistonjohn**
### What does this PR achieve? Why do we need it?

Adjust regex to allow device paths with colons. Colons may appear
in paths such as "/dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:1:0"
and thus are valid use cases.

### Does this PR fix issues?

Fixes #1246

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
@phlogistonjohn not merging this before #1253 . Will do a rebase and merge after that.

**Comment by phlogistonjohn** [comment]
np. I'm in no rush with this one.

**Comment by phlogistonjohn** [comment]
ping @obnoxxx  please review if you have some time

**Comment by raghavendra-talur** [comment]
@centos-ci retest this please

**Comment by obnoxxx** [comment]
centos-ci ssh connection error again

retest this please

**Comment by obnoxxx** [comment]
Strange, after more than an hour, in TestCreateClusterTLSCert and TestCreateClusterTLSNoVerify, we see

```
08:09:34 === RUN   TestCreateClusterTLSCert
08:09:35 --- FAIL: TestCreateClusterTLSCert (0.40s)
08:09:35 	assert.go:44: 
08:09:35 		
ASSERT:	func (github.com/heketi/heketi/tests/functional/TestEnabledTLS/client_tls_test_test.testClientActions) 0x6846e4
08:09:35 		
	File /root/go/src/github.com/heketi/heketi/tests/functional/TestEnabledTLS/client_tls_test/client_tls_test.go:94
08:09:35 		
	Info: [expected err == nil, got: Post https://localhost:8080/clusters: dial tcp [::1]:8080: getsockopt: connection refused]
08:09:35 === RUN   TestCreateClusterTLSNoVerify
08:09:35 --- FAIL: TestCreateClusterTLSNoVerify (0.40s)
08:09:35 	assert.go:44: 
08:09:35 		
ASSERT:	func (github.com/heketi/heketi/tests/functional/TestEnabledTLS/client_tls_test_test.testClientActions) 0x6846e4
08:09:35 		
	File /root/go/src/github.com/heketi/heketi/tests/functional/TestEnabledTLS/client_tls_test/client_tls_test.go:94
08:09:35 		
	Info: [expected err == nil, got: Post https://localhost:8080/clusters: dial tcp [::1]:8080: getsockopt: connection refused]
```

Cannot be related..

**Comment by obnoxxx** [comment]
retest this please

**Pull request merged**
