### PR TITLE
Fix the v10.4 release module name

### LINKED ISSUE #1897: go mod download github.com/heketi/heketi@v10.4.0 fails
### Kind of issue
 
Bug

### Observed behavior

`go mod download github.com/heketi/heketi@v10.4.0` fails with the following message:

```
$ go mod download github.com/heketi/heketi@v10.4.0
go: github.com/heketi/heketi@v10.4.0+incompatible: invalid version: module contains a go.mod file, so module path must match major version ("github.com/heketi/heketi/v10")
```

### Expected/desired behavior

Kubernetes script for updating dependencies uses `go mod download` command and the v10.4.0 prevents us from upgrading. Please note, that the previous version worked fine:

```
$ go mod download github.com/heketi/heketi@v10.3.0
$ echo $?
0
```

### Details on how to reproduce (minimal and precise)

```
$ go mod download github.com/heketi/heketi@v10.4.0
go: github.com/heketi/heketi@v10.4.0+incompatible: invalid version: module contains a go.mod file, so module path must match major version ("github.com/heketi/heketi/v10")
```

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v10.4.0
- Operating system used: Linux
- Heketi compiled from sources, as a package (rpm/deb), or container: referenced from Kubernetes repo
- Using kubernetes, openshift, or direct install: Kubernetes repo, see https://github.com/kubernetes/kubernetes/issues/104007
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): 

### Other useful information

xref: https://github.com/kubernetes/kubernetes/issues/104007

### PR DESCRIPTION
**Pull request by slaskawi**
### What does this PR achieve? Why do we need it?

This Pull Request adds the `v10` prefix to the module names, so that we can pull them into the kubernetes repo.

### Does this PR fix issues?

Fixes #1897

### Notes for the reviewer

We will need another release containing this commit.

### CODE REVIEW

**Comment by humblec** [comment]
lgtm

**Comment by humblec** [comment]
@raghavendra-talur @phlogistonjohn can you please review this PR please ?

**Comment by slaskawi** [comment]
@raghavendra-talur @phlogistonjohn Just a friendly reminder.

**Comment by slaskawi** [comment]
I see there are failures in the CI. Let me have a look at them and get back to you with a fix (if needed).

**Comment by slaskawi** [comment]
@raghavendra-talur - Could I ask you to retrigger the CI? I think I found the root problem and fixed it.

**Comment by slaskawi** [comment]
@iamniting It seems we'll need an `/ok-to-test` from @raghavendra-talur or someone else, who can trigger the CI.

It should be fine, I tested this in my fork: https://github.com/slaskawi/heketi/pull/1

**Comment by phlogistonjohn** [comment]
The changes look pretty reasonable on first skim. However, it does touch a lot of lines of code and that makes me a little nervous because we don't spend time on heketi and it could be easy to miss something.
That said, I'll try to find some time soon to look this over more thoroughly later this week.

One last thing, we like to have all our changes "build" so splitting the go mod change from the import lines changes causes the build to break on that first commit. I simply suggest to squash the patches together, thanks!

**Comment by slaskawi** [comment]
> The changes look pretty reasonable on first skim. However, it does touch a lot of lines of code and that makes me a little nervous because we don't spend time on heketi and it could be easy to miss something.
That said, I'll try to find some time soon to look this over more thoroughly later this week.

@phlogistonjohn That's great! Thank you!

If you'd like to give it a go from a Heketi client code perspective, just try to upgrade to the latest version in Kubernetes repo (link)[https://github.com/kubernetes/kubernetes/blob/master/go.mod#L52]. The easiest way to do it is to call `hack/pin-dependency.sh github.com/heketi/heketi v10.4.0` (with the latest version of course!) and check if it passes.

> One last thing, we like to have all our changes "build" so splitting the go mod change from the import lines changes causes the build to break on that first commit. I simply suggest to squash the patches together, thanks!

@phlogistonjohn Squashed and re-pushed.

**Comment by slaskawi** [comment]
Did you have a chance to look into this @@phlogistonjohn ?

**Comment by slaskawi** [comment]
Just a friendly reminder, @phlogistonjohn

**Review by phlogistonjohn — APPROVED** [review]
This is a large set of changes but they're pretty straightforward.

I assume that no one will be able to benefit from these until we do a release. So, we'll plan on doing one soon - but I can't say how soon yet because, as you know, we have very little time to spare for heketi these days. I will aim to do a release sometime before the end of June at the latest.

**Comment by phlogistonjohn** [comment]
Oddly, the centos ci doesn't appear to be running (yet).  I want to ensure all tests are run even if everything looks good to us humans.

If centos ci doesn't run by tomorrow, we may need to reach out to that team. Let's keep an eye on this.

**Comment by slaskawi** [comment]
Everything seems to be green now :tada: 

I'd just need a tag, so that I can bump it in k/k repo.

**Comment by slaskawi** [comment]
Hey @phlogistonjohn !

I just got back from my PTO and wanted to get this rolling. Could I kindly ask you to have a look at it and create a tag, so that I can bump this in k/k repo? 

//cc @humblec

**Comment by humblec** [comment]
lgtm.. also all tests are green :+1:

**Comment by phlogistonjohn** [comment]
Please bear with us, there are supposed to be additional tests run as part of the centosCI but they're missing from the status entirely. Our contact was also on extended PTO and only recently returned.

**Comment by slaskawi** [comment]
> Please bear with us, there are supposed to be additional tests run as part of the centosCI but they're missing from the status entirely. Our contact was also on extended PTO and only recently returned.

@phlogistonjohn No problem! Please take all the time you need to execute those tests.

**Comment by phlogistonjohn** [comment]
Infrastructure looks like it's been fully revived. A test failed but the failure looks like it could be a test flake. I'll restart the CI run and see if it fails again in the same place.

**Comment by phlogistonjohn** [comment]
@raghavendra-talur   I'd like a 2nd review please.

**Comment by slaskawi** [comment]
@phlogistonjohn @raghavendra-talur Could have one more small request for? Could you please tag the new release? I'll start the bump in k/k repo then.

**Comment by slaskawi** [comment]
@phlogistonjohn ooh I missed it. Thanks for pointing it out. Let me continue the discussion there.

**Pull request merged**
