### PR TITLE
bring the python api into the test script fold

### PR DESCRIPTION
**Pull request by phlogistonjohn**
This series:
* Creates test scripts that check python code and run unit tests using our new framework
* Drop old cruft
* Use a better python test runner
* Get the python api code running under python3

### CODE REVIEW

**Comment by pkkid** [comment]
Checks failed on this one.

**Comment by raghavendra-talur** [comment]
@phlogistonjohn Please rebase the patch :)

**Comment by phlogistonjohn** [comment]
I thought I would just do a quick rebase, but this little test suite tweak seems to be rather fraught with peril, at least far as travis is concerned. I'll try to deal with this soon.

**Comment by obnoxxx** [comment]
I like the thought of this patch! But the result is weird. The travis output is:
```
$ pyenv global system 3.5

pyenv: version `3.5' not installed
```
Not sure about this `pyenv` command - I don't have it on my system. But locally, the new python test script passes for me, without calling pyenv.

**Comment by phlogistonjohn** [comment]
Its a travis/ubuntu thing AFAICT. This is pretty high on my priority list to get back to but I still haven't had a chance to look at it. I usually like to test stuff locally before I push but that's more challenging with travis. I hope to find time to spend on this soon.

**Comment by obnoxxx** [comment]
> Its a travis/ubuntu thing AFAICT.

"It" being `pyenv`?

> I usually like to test stuff locally before I push but that's more challenging with travis.

Right. Just running the tests locally is not the problem. The (travis) environment setup seems to be the challenge here. You can set up travis to track and build your personal repos, see e.g.  https://travis-ci.org/obnoxxx/heketi. So in theory, you can test without the need to file a PR. But there are some issues with that, for example the security stuff does not work...

**Comment by obnoxxx** [comment]
There seems to be a problem in running a go project from a forked location:

```
go build -i -ldflags "-X main.HEKETI_VERSION=v2.0.6-462-ge37be79-HEAD -extldflags '-z relro -z now'" -o heketi

# github.com/obnoxxx/heketi

./main.go:158: cannot use heketiRouter (type *"github.com/obnoxxx/heketi/vendor/github.com/gorilla/mux".Router) as type *"github.com/heketi/heketi/vendor/github.com/gorilla/mux".Router in argument to app.SetRoutes

make: *** [heketi] Error 2
```
:-o

**Comment by phlogistonjohn** [comment]
OK, I think I have a version that is a bit more robust that before. Please (re)review.

**Pull request merged**
