### PR TITLE
Templates: Strategy to be in spec of dc

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Strategy and trigger are dc spec objects, Removing it from template.

Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by lpabon** [comment]
@MohamedAshiqrh Yes, they are dc spec, so that is why they are here.  A template is really just a List object, and a List object is a collection of objects.  The DeploymentConfig section uses the triggers.

Please let me know if I am wrong, but as far as I can tell, this is the way a template works.

**Comment by MohamedAshiqrh** [comment]
@lpabon yeah, you are right. It should be in dc spec but it's inside template list which does not  have strategy and trigger object. so dc is taking default rolling strategy, if you use the template. Just for clarity see the example https://github.com/openshift/origin/blob/master/docs/deployments.md .

**Comment by humblec** [comment]
@lpabon ACK from my side. :+1:

**Comment by lpabon** [comment]
ok to test @centos-ci

**Comment by lpabon** [comment]
retest this please @centos-ci

**Comment by lpabon** [comment]
There seemed to be an error in the ci test

**Comment by lpabon** [comment]
retest this please @centos-ci

**Comment by lpabon** [comment]
retest this please @centos-ci

**Comment by lpabon** [comment]
CentOS CI hit #445. Trying again

**Comment by lpabon** [comment]
retest this please @centos-ci

**Comment by lpabon** [comment]
retest this please @centos-ci

**Comment by lpabon** [comment]
retest this please @centos-ci

**Comment by lpabon** [comment]
retest this please @centos-ci

**Comment by lpabon** [comment]
retest this please @centos-ci

**Comment by lpabon** [comment]
This is really weird.  I'm not sure how, but the proxy is intercepting the message, which exposes the panic in the heketi cli.

**Comment by lpabon** [comment]
retest this please @centos-ci

**Comment by lpabon** [comment]
@MohamedAshiqrh With this patch, it seems deploy-heketi cannot be deployed.  From centos-ci:

```
TASK [client : install topology in deploy-heketi] ******************************
fatal: [client]: FAILED! => {"changed": true, "cmd": ["heketi-cli", "-s", "http://deploy-heketi-default.cloudapps.example.com", "topology", "load", "--json=topology.json"], "delta": "0:00:00.061595", "end": "2016-09-19 21:18:46.138916", "failed": true, "rc": 255, "start": "2016-09-19 21:18:46.077321", "stderr": "Error: Unable to get topology information: ", "stdout": "", "stdout_lines": [], "warnings": []
```

Without the patch, everything works as expected.  Do you mind checking out what is going on here?

**Comment by MohamedAshiqrh** [comment]
@lpabon looking into it.

**Comment by lpabon** [comment]
retest this please @centos-ci

**Comment by MohamedAshiqrh** [comment]
Got it, yay. So the deployment strategy for deploy-heketi is replace. There is no such strategy. So how is it passing now? oh great we have the strategy in wrong place so it always sets to default(which is rolling).

**Comment by MohamedAshiqrh** [comment]
Good that we have CI, @lpabon  :+1: .

**Comment by MohamedAshiqrh** [comment]
@lpabon passed the test.

**Comment by lpabon** [comment]
@MohamedAshiqrh :+1:  for CI!

**Pull request merged**
