### PR TITLE
clean Makefile and avoid skipping heketi building

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
@heketi/maintainers PTAL

@obnoxxx This will help to build faster, can we merge this to avoid build delay.

**Comment by MohamedAshiqrh** [comment]
@raghavendra-talur can you review?

**Comment by MohamedAshiqrh** [comment]
@lpabon PTAL

**Comment by obnoxxx** [comment]
@MohamedAshiqrh thanks. I have to say that I am doubtful about this patch. Will follow up later...

**Comment by lpabon** [comment]
LGTM. Seems to do the same. Travis confirmed it works. I'll let @obnoxxx comment.

**Comment by obnoxxx** [comment]
I said I'm skeptical about the patch because it seems conceptually weird. It just exchanges the roles of server and heketi in the Makefile. Why does it work? It works because "server" is a .PHONY target, hence it gets executed always, in contrast to "heketi" which is only executed when the the heketi file is older than the deps. In a real Makefile/buildsystem, there would be dependencies to all files needed for the build (i.e. in particular the source files, and not only glide.lock and vendor). But here this does not exist.

By changing the dependency and rule roles, so that heketi depends on the .PHONY server target, heketi gets always built. This is not wrong as such. But idiomatically, it "feels wrong" to have the "meta target" server depend on the concrete file target heketi. In (the theoretical) case we would want to add more server components to the server target again, we'd need to revise this patch again.

So I currently see one conceptually more satisfying alternative solution:

* make the heketi target .PHONY ==> Proposed in PR #788

Since we don't have dependency tracking for heketi sources, this is only
fair. And it achieves the same effect that is patch achieves implicitly.

On top of that, we might think about removing the "server" target altogether.

**Comment by lpabon** [comment]
@obnoxxx good points. I'll let you and @MohamedAshiqrh decide what to do.

**Comment by MohamedAshiqrh** [comment]
Closing this as #788 fixes this in right way. @obnoxxx thanks for the explanation.

**Pull request closed without merging**
