### PR TITLE
apps:glusterfs: store the allocator in the app again.

### PR DESCRIPTION
**Pull request by obnoxxx**
Previously, the allocator was not stored in the app
to prevent stale data as loaded from the db. Now that
the data is always loaded freshly in GetNodes(),
the stored allocator is not really a cache any more
but basically reflects the chosen allocator methods.
So at app start, we instantiate and store the configured
allocator again.

Signed-off-by: Michael Adam <obnox@redhat.com>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Test failures look to be due to gopkg.in hiccup.

**Comment by phlogistonjohn** [comment]
The more I think about it, I'd rather see the internals of the allocator (re)moved so that they exist only within GetNodes. Then we can remove the mutex and know the rings exist only within the single transaction. This might mean creating an intermediate type to hold the ring first though.

**Comment by phlogistonjohn** [comment]
@obnoxxx see pr #1078 for a mostly-fleshed-out version of what I was talking about in my previous comment.

**Comment by obnoxxx** [comment]
I continues this work in PR #1082 .

**Comment by obnoxxx** [comment]
superseded and obsoleted by #1086 .

**Pull request closed without merging**
