### PR TITLE
check for self heal before replaceBrick

### PR DESCRIPTION
**Pull request by obnoxxx**
The conditions to be considered are
1. If the brick to be replaced is source for some files, don't proceed
2. We kill the brick to be replaced, if that would make the replica set
lose quorum, don't proceed.

This has a side effect that remove device won't work on volumes which
have replica count 2. Choosing data safety over migration features.

Signed-off-by: Raghavendra Talur <rtalur@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
This is a rebase of PR #718  and should replace that pr.

**Comment by obnoxxx** [comment]
LGTM

**Comment by obnoxxx** [comment]
According to @lpabon 's LGTM barring rebase and CI test pass, which happened here now, I am merging.

**Comment by lpabon** [comment]
:+1:

**Pull request merged**
