### PR TITLE
Logging: Volume create error message to be logged

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
#609 
Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
@heketi/dev please review

**Comment by obnoxxx** [comment]
@centos-ci ok to test

**Comment by obnoxxx** [comment]
is that a flakiness in the vagrant setup?

@centos-ci retest this please

**Comment by obnoxxx** [comment]
lgtm but want the tests to pass...

**Comment by humblec** [comment]
LGTM

**Comment by MohamedAshiqrh** [comment]
Looks like not with respect to patch.

```
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
==> ERROR: unable to start vagrant virtual machines
==> FAILED TestVolumeSnapshotBehavior
==> TEARDOWN TestVolumeSnapshotBehavior
```

**Comment by obnoxxx** [comment]
@MohamedAshiqrh i don't know who you ask to fix the errors? I don't know about it... :-(

I have been running the functional tests for the various PRs locally since last night. The bringing up of VMs works fine, but there are genuine test failures. Not necessarily related. I am investigating...

**Comment by obnoxxx** [comment]
@MohamedAshiqrh the *actual* error is:

```
[sshexec] ERROR 2016/12/07 10:35:00 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:158: Failed to run command [sudo /bin/bash -c 'gluster --mode=script volume create vol_e61e052eafe57fadb610e0c100f3b704 replica 2 192.168.10.103:/var/lib/heketi/mounts/vg_7ea2204b36a51cc4e0fc21ccf375bb65/brick_b985b61fc351b17b53ea9195e62f9d69/brick 192.168.10.100:/var/lib/heketi/mounts/vg_4f30d3c2d981bf3040a337ef95a652d1/ brick_95e751e3ce8d4d6eba4515f19a29a1eb/brick '] on 192.168.10.103:22: Err[Process exited with: 1. Reason was:  ()]: Stdout []: Stderr [volume create: vol_e61e052eafe57fadb610e0c100f3b704: failed: Host 192.        168.10.100 is not in ' Peer in Cluster' state
```

**Comment by obnoxxx** [comment]
but is not related to this patch

**Pull request merged**
