### PR TITLE
Smallish refactoring in prep for more volume delete work

### PR DESCRIPTION
**Pull request by phlogistonjohn**
### What does this PR achieve? Why do we need it?

Various small refactoring of code in apps preparing for the volume delete behavior of auto-cleanup.

### Notes for the reviewer

This PR builds upon PR #1400 - please review and merge that PR first.

### CODE REVIEW

**Comment by obnoxxx** [comment]
@phlogistonjohn rebased for you :-)

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
@phlogistonjohn what did you change in the last update?

**Comment by phlogistonjohn** [comment]
> @phlogistonjohn what did you change in the last update?

Sorry, but I don't remember. I just rebased again & pushed before I saw your message.

**Comment by obnoxxx** [comment]
ok!

**Pull request merged**
