### PR TITLE
Direct kubernetes users to gluster-kubernetes

### LINKED ISSUE #1177: update DOC for extras/kubernetes
Hi,

in extras/kubernetes. deploy-heketi-deployment.json still used in the Readme.md file otherwise it does not exist in the files. as consequence i am unable to install it properly.

thank you

### PR DESCRIPTION
**Pull request by joejulian**
This documentation has been deprecated. Instead, direct users to install
using gluster-kubernetes.

Fixes #1177, #931, #873, #820, #807, #587

### CODE REVIEW

**Comment by nixpanic** [comment]
ok to test

**Comment by joejulian** [comment]
Sounds good. Done.

**Comment by phlogistonjohn** [comment]
I'd like to preserve some of this document (under a different name perhaps) as its the only prose documentation that shows how heketi works with kubernetes. Directing people away from this doc for production is great. However, I'd hate to lose some of the institutional knowledge it contains (git history doesn't count due it's low discover-ability).

Can we rename the doc to something like "how heketi integrates with kubernetes" and orient it more towards a document for those who are curious about how heketi works and/or potential contributors?

**Comment by joejulian** [comment]
I tried following those docs and when I failed, I looked in issues and saw that everyone was being pointed to gk-deploy. Leaving them in would imply some sort of maintained correctness which, afaict, isn't the case.

Do any of the maintainers have the time or inclination to maintain any of this? If so, which bits should remain and be maintained? I'll happily make the change to this PR.

**Comment by phlogistonjohn** [comment]
I went through that guide and updated issues that I found within the last 4 months or so. But like I mentioned, I see this as more developer oriented docs telling people how the peices fit together rather than a guide on how to get heketi running in kubernetes for production. I think most people want the latter and that's why they get pointed at things like g-k  or openshift ansible.

Personally, I"d just start by renaming the doc (both the filename and the title). Perhaps moving it out from under admin and under design and putting more emphasis in the into that this is background rather than a complete HOW-TO. I'd retain the majority of the body of the doc. As for the templates, I think we can discuss if we want to simply refer to the templates that live in g-k and completely remove them from this repo or move them somewhere under the docs tree.

**Comment by phlogistonjohn** [comment]
@joejulian any interest in this still? If you've lost interest in this PR I can make an alternative PR that does as I requested: rename original doc, add more strenuous pointer to g-k, reword starting section of current doc to indicate is is for developer & educational purposes.

Any thoughts?

**Comment by jarrpa** [comment]
@phlogistonjohn I'd say ten days is more than enough time to wait for a response. Probably fine to go ahead with your idea.

**Comment by phlogistonjohn** [comment]
Good point. It will probably take me a few to get my PR together anyway. :-)

**Pull request closed without merging**
