### PR TITLE
[WIP] separate test log from server logs

### PR DESCRIPTION
**Pull request by raghavendra-talur**
Signed-off-by: Raghavendra Talur <rtalur@redhat.com>

### Does this PR fix issues?

Fixes #

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
Noting down that the TestAdminModes tests passed with the two original commits in this PR.

```
--- PASS: TestAdminModes (152.04s)
    --- PASS: TestAdminModes/testAdminStatusGet (0.00s)
    --- PASS: TestAdminModes/testAdminStatusLocal (5.65s)
    --- PASS: TestAdminModes/testAdminStatusNormal (12.70s)
    --- PASS: TestAdminModes/testAdminStatusReadOnly (0.00s)
    --- PASS: TestAdminModes/testAdminStatusReset (5.24s)
```

**Comment by raghavendra-talur** [comment]
Noting down the test result after adding the two commits from #1707 

```
23:06:46 === RUN   TestAdminModes
23:08:17 --- FAIL: TestAdminModes (90.81s)
23:08:17     assert.go:44: 
23:08:17         
ASSERT:	func (github.com/heketi/heketi/pkg/testutils.(*ClusterEnv).SetupWithCluster) 0x713527
23:08:17         
	File /root/go/src/github.com/heketi/heketi/pkg/testutils/cluster.go:152
23:08:17         
	Info: [expected err == nil, got: Get http://localhost:8080/queue/22e7995bf5bc8d744a339b19a89a3bb3: dial tcp: lookup localhost: device or resource busy]
```

**Comment by phlogistonjohn** [comment]
@raghavendra-talur do we still need this?

**Comment by raghavendra-talur** [comment]
This was only an experiment. Closing.

**Pull request closed without merging**
