### PR TITLE
fixed govet errors in test cases

### PR DESCRIPTION
**Pull request by Madhu-1**
Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
ok to test

**Comment by raghavendra-talur** [comment]
@centos-ci ok to test

**Comment by phlogistonjohn** [comment]
I'm +0 on breaking it up. It isn't strictly needed but could be a good exercise.

**Comment by Madhu-1** [comment]
@phlogistonjohn  am using go 1.10 , while running  Make test am able to find this go vet issues.

**Comment by phlogistonjohn** [comment]
Thanks @Madhu-1 I thought that might be the case but I wanted to be sure. :-)

We should consider adding newer Go versions to our travis tests. I'm going to file an issue to track that so I don't forget.

**Pull request merged**
