### PR TITLE
Cleanup allocator more

### PR DESCRIPTION
**Pull request by obnoxxx**
This is a continuation of the work begun in PR #1078.
It takes the patch from that PR and further simplifies and cleans up the code in simple_allocator.go.
Now the ring really only exists as stack variables below GetNodes.

### CODE REVIEW

**Comment by obnoxxx** [comment]
As a consequence, we could (safely) use the patch from PR #1064 on top of this, to store the allocator in the app again.

**Comment by obnoxxx** [comment]
Or alternatively, remove the whole instantiate an allocator when we start the app business from app.go ... :-)

**Comment by phlogistonjohn** [comment]
> Or alternatively, remove the whole instantiate an allocator when we start the app business from app.go ... :-)

That's the approach I prefer.

**Comment by obnoxxx** [comment]
@phlogistonjohn if you like it, feel free to merge.
I am writing on getting rid of the allocator stuff from app.go.

**Comment by obnoxxx** [comment]
@phlogistonjohn wrote:
> I especially think that loadRingFromDB will come in handy in the upcoming arbiter work.

I hope that the signature change that this introduces does not turn out disadvantageous.
We might want to use GetDevicesFromDB instead.

**Pull request merged**
