### PR TITLE
Node Remove: Removes all the device in the node

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Node Remove is called to migrate all the bricks in device associated to a node.

What is done here?
1) First the devices of the node removed from the ring.
2) then device remove is called for each device of node.
3) If one device failed to remove then node remove fails.
4) while exiting It adds the devices back to ring.

Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
@heketi/maintainers Please review this.

**Comment by MohamedAshiqrh** [comment]
@humblec @obnoxxx @lpabon Take a look at this.

**Comment by lpabon** [comment]
Oops, wrong button.  I'll take a look at this patch after I review #676.  I know it is merged already, but it needs to be reviewed.

**Comment by obnoxxx** [comment]
@lpabon saying that #676 needs to be reviewed, implies that it has not been reviewed yet, which is not true... If you're saying that you want to review it some more and then come back and review this PR, that's of course very valid.

So do I get the do-not-merge label right as an indication that you want to ask for not merging until you have reviewed it? Just putting it up feels a little odd... :-)

**Comment by obnoxxx** [comment]
@MohamedAshiqrh this needs to be rebased.

@lpabon now that the remove disk functionality is merged, we should reconsider this one, which builds on it.

**Comment by lpabon** [comment]
@obnoxxx Absolutely. This should follow the same architecture as the merged "remove disk" functionality.

**Comment by MohamedAshiqrh** [comment]
#752 is the new PR.

Closing this as everything is addressed in the new PR.

**Pull request closed without merging**
