### PR TITLE
heketi-cli: Bash auto-completion file

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
How to test:

copy this file to /usr/share/bash-completion/completions/ then source it.

`# cp heketi-cli.sh /usr/share/bash-completion/completions/`

`# source  /usr/share/bash-completion/completions/heketi-cli.sh`

now you are good to go.

NOTE: this is still WIP. not working in zsh, can send the support later too.

Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by lpabon** [comment]
This is super cool. I'll need to set some time tomorrow or Thursday to try it out

**Comment by MohamedAshiqrh** [comment]
@lpabon thanks. sure take your time and try out in your mac too, Just curious to see if it works. I dont know how different it is though.

**Comment by lpabon** [comment]
Closes #476

**Comment by lpabon** [comment]
This is _freakin_ awesome! Thanks.  I'll add it to the Fedora RPM next release

**Pull request merged**
