### PR TITLE
Kubernetes Deployment Suppor and Tests

### LINKED ISSUE #507: heketi-cli volume create fails Error No space (volume_entry_allocate.go (66) Id not found
Hello,

While running heketi-cli volume create --size=11 --replica=1 --redundancy=1  --durability=none --persistent-volume-endpoint=10.0.2.15 --clusters=7b377075af001357f34c748df02d1ebc

... I get the error below. 
Please be more specific how to create volume in gluster kubernetes pods. Is it the existence of a raw device a prerequisite? Can you describe the steps one by one how could someone use heketi-cli volume create for a glusterfs pod? What should look like the ep, pv, pvc, svc and gluster pod manifest files (yaml or Json no matter). It is nowhere clear of the exact steps except for ssh cases without kubernetes but this is not my case.

Sep 20 19:54:47 localhost.localdomain heketi[722]: [asynchttp] INFO 2016/09/20 19:54:47 Started job 62022beb0b0525afbe1fcf827f30a693
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] INFO 2016/09/20 19:54:47 Creating volume 28c3a6c13145ae86faf75a6de1f54102
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] DEBUG 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry.go:255: Using the following clusters: []
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] DEBUG 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:44: brick_size = 5767168
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] DEBUG 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:48: sets = 2
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] INFO 2016/09/20 19:54:47 brick_num: 0
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] ERROR 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/allocator_simple.go:164: Unknown cluster id requested: 7b377075af0
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] DEBUG 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:120: 0 / 1
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] DEBUG 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:87: Error detected.  Cleaning up volume 2
Sep 20 19:54:47 localhost.localdomain heketi[722]: [negroni] Started GET /queue/62022beb0b0525afbe1fcf827f30a693
Sep 20 19:54:47 localhost.localdomain heketi[722]: [negroni] Completed 200 OK in 41.255µs
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] ERROR 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:66: Id not found
Sep 20 19:54:47 localhost.localdomain heketi[722]: [heketi] ERROR 2016/09/20 19:54:47 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:131: Failed to create volume: No space
Sep 20 19:54:47 localhost.localdomain heketi[722]: [asynchttp] INFO 2016/09/20 19:54:47 Completed job 62022beb0b0525afbe1fcf827f30a693 in 14.522612ms
Sep 20 19:54:48 localhost.localdomain heketi[722]: [negroni] Started GET /queue/62022beb0b0525afbe1fcf827f30a693
Sep 20 19:54:48 localhost.localdomain heketi[722]: [negroni] Completed 500 Internal Server Error in 38.979µs

### LINKED ISSUE #508: Use a service account to access Kubernetes
Instead of using user/pass so that Heketi can communicate with Kubernetes server, use a service account specifically setup for Heketi.  This is the same method used to deploy the following services:  logging, registry, and metrics in OpenShift

### LINKED ISSUE #521: No space error with kubernetes
Hello,

finally I can load a topology file but when I try to create a volume I got this message:

```
[root@oam-node-1 /]# heketi-cli -s http://localhost:8082 volume create --size=5
Error: No space

```
Any idea? I attach every information what can be important, ifI forget something just ask it :) Thanks

Topology info: 

```
[root@jinja2-test-build171-oam-node-1 /]# heketi-cli -s http://localhost:8082 topology info

Cluster Id: d2120f290f7ab4ab17b760fb86599894

    Volumes:

    Nodes:

        Node Id: 8e39d70e542c54361e0de306593c1f3c
        State: online
        Cluster Id: d2120f290f7ab4ab17b760fb86599894
        Zone: 1
        Management Hostname: gluster1
        Storage Hostname: 172.24.16.104
        Devices:
                Id:524314b04d36b1056bd708092d04ed4c   Name:/dev/vdd            State:online    Size (GiB):19      Used (GiB):0       Free (GiB):19
                        Bricks:

```
I'm using heketi in [docker ](https://hub.docker.com/r/heketi/heketi/) and gluster with kubernetes ([image](https://hub.docker.com/r/gluster/gluster-centos/)). 

Heketi config:
```
{
  "port": "8082",
  "use_auth": false,
  "glusterfs": {
    "executor": "kubernetes",
    "kubeexec": {
      "host" :"http://127.0.0.1:8080",
      "insecure": true,
      "user": "kube",
      "password": "",
      "namespace": "kube-system",
      "fstab": "/etc/fstab"
    },
    "db": "/var/lib/heketi/heketi.db",
    "loglevel" : "debug"
  }
}

```
and I set: 
`HEKETI_KUBE_USE_POD_NAMES="1"`

Hekete log: 

```
Listening on port 8082
[negroni] Started GET /clusters
[negroni] Completed 200 OK in 1.302804ms
[negroni] Started POST /clusters
[negroni] Completed 201 Created in 479.277956ms
[negroni] Started POST /nodes
[heketi] INFO 2016/09/23 06:04:21 Adding node gluster1
[negroni] Completed 202 Accepted in 65.2514ms
[asynchttp] INFO 2016/09/23 06:04:21 Started job d6df7dc95026d80f12b33111775c0b30
[negroni] Started GET /queue/d6df7dc95026d80f12b33111775c0b30
[negroni] Completed 200 OK in 45.029µs
[heketi] INFO 2016/09/23 06:04:21 Added node 8e39d70e542c54361e0de306593c1f3c
[asynchttp] INFO 2016/09/23 06:04:21 Completed job d6df7dc95026d80f12b33111775c0b30 in 48.148865ms
[negroni] Started GET /queue/d6df7dc95026d80f12b33111775c0b30
[negroni] Completed 303 See Other in 36.449µs
[negroni] Started GET /nodes/8e39d70e542c54361e0de306593c1f3c
[negroni] Completed 200 OK in 254.599µs
[negroni] Started POST /devices
[heketi] INFO 2016/09/23 06:04:21 Adding device /dev/vdd to node 8e39d70e542c54361e0de306593c1f3c
[negroni] Completed 202 Accepted in 26.72112ms
[asynchttp] INFO 2016/09/23 06:04:21 Started job c94ae9124203333b68eae61cef902d83
[negroni] Started GET /queue/c94ae9124203333b68eae61cef902d83
[negroni] Completed 200 OK in 18.898µs
[kubeexec] DEBUG 2016/09/23 06:04:22 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:298: Host: gluster1 Command: pvcreate --metadatasize=128M --dataalignment=256K /dev/vdd
Result:   Physical volume "/dev/vdd" successfully created
[negroni] Started GET /queue/c94ae9124203333b68eae61cef902d83
[negroni] Completed 200 OK in 32.301µs
[kubeexec] DEBUG 2016/09/23 06:04:23 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:298: Host: gluster1 Command: vgcreate vg_524314b04d36b1056bd708092d04ed4c /dev/vdd
Result:   Volume group "vg_524314b04d36b1056bd708092d04ed4c" successfully created
[kubeexec] DEBUG 2016/09/23 06:04:23 /src/github.com/heketi/heketi/executors/kubeexec/kubeexec.go:298: Host: gluster1 Command: vgdisplay -c vg_524314b04d36b1056bd708092d04ed4c
Result:   vg_524314b04d36b1056bd708092d04ed4c:r/w:772:-1:0:0:0:-1:0:1:1:20836352:4096:5087:0:5087:xAJ0aO-6Scj-hyfV-Wm4n-CVBC-M4gq-TugTmX
[sshexec] DEBUG 2016/09/23 06:04:23 /src/github.com/heketi/heketi/executors/sshexec/device.go:126: Size of /dev/vdd in gluster1 is 20836352
[negroni] Started GET /queue/c94ae9124203333b68eae61cef902d83
[negroni] Completed 200 OK in 30.085µs
[heketi] INFO 2016/09/23 06:04:23 Added device /dev/vdd
[asynchttp] INFO 2016/09/23 06:04:23 Completed job c94ae9124203333b68eae61cef902d83 in 2.053853076s
[negroni] Started GET /queue/c94ae9124203333b68eae61cef902d83
[negroni] Completed 204 No Content in 28.867µs
[negroni] Started GET /clusters/d2120f290f7ab4ab17b760fb86599894
[negroni] Completed 200 OK in 168.222µs
[negroni] Started POST /volumes
[heketi] DEBUG 2016/09/23 06:04:50 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry.go:89: [f4b8c7bc5bb979e159f75dd972cf2553] Replica 3
[negroni] Completed 202 Accepted in 203.548µs
[asynchttp] INFO 2016/09/23 06:04:50 Started job d28380b162412efda1fec242846d46b2
[heketi] INFO 2016/09/23 06:04:50 Creating volume f4b8c7bc5bb979e159f75dd972cf2553
[heketi] DEBUG 2016/09/23 06:04:50 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry.go:255: Using the following clusters: []
[heketi] ERROR 2016/09/23 06:04:50 /src/github.com/heketi/heketi/apps/glusterfs/volume_entry_allocate.go:41: Minimum brick size limit reached.  Out of space.
[negroni] Started GET /queue/d28380b162412efda1fec242846d46b2
[negroni] Completed 200 OK in 19.891µs
[asynchttp] INFO 2016/09/23 06:04:50 Completed job d28380b162412efda1fec242846d46b2 in 71.40598ms
[heketi] ERROR 2016/09/23 06:04:50 /src/github.com/heketi/heketi/apps/glusterfs/app_volume.go:131: Failed to create volume: No space
[negroni] Started GET /queue/d28380b162412efda1fec242846d46b2
[negroni] Completed 500 Internal Server Error in 33.675µs
[negroni] Started GET /clusters
[negroni] Completed 200 OK in 63.76µs
[negroni] Started GET /clusters/d2120f290f7ab4ab17b760fb86599894
[negroni] Completed 200 OK in 145.526µs
[negroni] Started GET /nodes/8e39d70e542c54361e0de306593c1f3c
[negroni] Completed 200 OK in 227.731µs

```

### PR DESCRIPTION
**Pull request by lpabon**
This pull request combines PR #543 with a cleanup of TestKubeSmokeTest.

Closes #508 
Closes #521 
Closes #507 

Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>
Signed-off-by: Luis Pabón <lpabon@redhat.com>

### CODE REVIEW

**Comment by lpabon** [comment]
@nixpanic We seem to have a bug where we wait forever.  Who do we talk to about killing a jenkins job?

**Comment by lpabon** [comment]
@nixpanic See https://ci.centos.org/job/gluster_heketi-functional/116/

**Comment by nixpanic** [comment]
@lpabon there is a timeout on jobs, I think it is set to 24 hours by default. We could rewrite the job execution, @nigelbabu has an improved way to do it. Please check with him for options to set a maximum run time.

**Comment by lpabon** [comment]
@MohamedAshiqrh What we need to do now is add documentation on the Wiki for Kubernetes

**Pull request merged**
