### PR TITLE
apps: simplify logic a bit in BlockVolumeDestroy()

### PR DESCRIPTION
**Pull request by obnoxxx**
No semantic change. Just slight code improvement.

### CODE REVIEW

**Comment by obnoxxx** [comment]
@phlogistonjohn good point, but I'd rather avoid comments and put the message in log instead, e.g. like so:

```golang
if e := json.Unmarshal([]byte(errOutput), &blockVolumeDelete); e != nil {
    if r.Err != nil {
       return logger.LogErr("Failed to unmarshal response from block volume delete for volume %v: %v", blockVolumeName, r.Err)
    }

    return logger.LogError("Failed to unmarshal response from blockvolume delete for volume %v: Unable to parse result: %v", blockVolumeName, e)
}
```

What do you think?

**Comment by phlogistonjohn** [comment]
> 
> What do you think?

Usually, I'd be OK with this but in this case I'm wary of changing the error type on the return statement. Change it back to `return err` and log above and I'll be OK with it.

**Comment by obnoxxx** [comment]
@phlogistonjohn I changed it as suggested. PTAL (again)

**Comment by obnoxxx** [comment]
I kept them separate so we could have that discussion.
I would keep the first patch separate, because that's just the logic streamlining, and squash the other two, which add debug messages. Sounds OK?

**Comment by phlogistonjohn** [comment]
Yes

**Comment by obnoxxx** [comment]
@phlogistonjohn squashed as discussed and rebased

**Comment by phlogistonjohn** [comment]
retest this please

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
yay, all passed.
@phlogistonjohn can we merge?

**Comment by phlogistonjohn** [comment]
Yes. :-)

**Pull request merged**
