### PR TITLE
docs: add missing docs for node and device replacement

### LINKED ISSUE #1782: How to trigger movement of bricks from failed device to new device?
### Kind of issue

Feature request

### Observed behavior

Function exists https://github.com/heketi/heketi/blob/v10.0.0/apps/glusterfs/device_entry.go#L442 to remove bricks from a failed device and allocate onto unused devices but cannot see how to trigger this from heketi-cli or API.

### Expected/desired behavior

Trigger `removeBricksFromDevice` via heketi-cli or API so it is possible to "drain" a failed device by moving those failed bricks to point to new bricks on other available devices - either by replacing a disk or adding an entire new server to the cluster.

### Details on how to reproduce (minimal and precise)

Currently the delete/disable code is not working (https://github.com/heketi/heketi/issues/953) and older issues. Our team is experiencing issues replacing nodes because of this. We are considering DB export, manual fixup with gluster command, DB edit and DB re-import to resolve these. Clearly that is not a long-term solution.

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): v10.0
- Operating system used: CentOS 7
- Heketi compiled from sources, as a package (rpm/deb), or container: RPM from v10.
- If container, which container image: 
- Using kubernetes, openshift, or direct install: Direct install.
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: Outside.
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): Custom Ansible-based.

### Other useful information

Device or Node recovery seems neglected but it's a quality of life item for end-users and would make Heketi much more useful for the entire storage lifecycle and avoid complex work-around which can themselves threaten the integrity of the Heketi DB.

### PR DESCRIPTION
**Pull request by phlogistonjohn**
### What does this PR achieve? Why do we need it?

despite answering similar questions in the past I had not realized we didn't have proper documentation for node and device replacement/removal until now. This change aims to fill that gap.

### Does this PR fix issues?

Fixes #1782

### CODE REVIEW

**Comment by amehub** [comment]
It is unclear how to hot swap a failed disk.    If I have a 3 node heketi/gluster replicate:3 for all volumes and a disk dies I simply want to pull the failed disk out and replace it with a new disk and for heketi to sync the bricks with minimal operator effort.   Is hot swap device supported?

**Comment by phlogistonjohn** [comment]
I have not tried that exact scenario, but in theory it should work. However Heketi won't automatically make use of the replacement disk. The command sequence I would try would look something like:

* heketi-cli disable <bad-device-id>
(physically replace hard disk)
* heketi-cli device add <new-disk-params>
* heketi-cli device remove <bad-device-id>
* heketi-cli device delete [--force-forget] <bad-device-id>

The only concern I have is that heketi fully understands that the new device is valid for replacement when on the same node. I think it should work but never tried it myself.  If you're able to try it out please let me know if it worked for you and I'll add that as a scenario to the doc.

**Review by raghavendra-talur — APPROVED** [review]

**Review by iamniting — APPROVED** [review]

**Comment by amehub** [comment]
Hi

I have worked through the doc to replace a node.  I had 3 node gluster and a spare node.

gluster-01 )
gluster-02 ) Replicate:3 volume 
gluster-03 )
gluster-04 (the spare node not yet in the cluster)

I shutdown gluster-03 to simulate a complete failure of the node.  I then added gluster-04 to the topology file and loaded the topology file.  I watched as the bricks and files appeared on gluster-04.

```
sh-5.0# heketi-cli node disable a0da56ca7aa5d6b0a0e749f69b298076   # gluster-03
Node a0da56ca7aa5d6b0a0e749f69b298076 is now offline
```

To fully remove the bricks from the node, execute:

```
sh-5.0# heketi-cli node remove a0da56ca7aa5d6b0a0e749f69b298076    # gluster-03
Error: Error destroying old brick: dial tcp 192.168.1.133:22: connect: no route to host
```

However, 

`heketi-cli topology info `

reports that there are 4 nodes 
gluster-03 is still present and reporting that it has a brick.  I shut it down so to all intents and purposes it burst into flames and is gone forever.
gluster-04 (the replacement node) is present but reporting that it has no bricks.  I can see bricks and files on gluster-04.

The gluster nodes all think there are 3 peers. I think there should only be 2 peers and expected heketi-cli node remove to remove gluster-03 from gluster.

```
root@gluster-01:~# gluster peer status
Number of Peers: 3

Hostname: 192.168.1.133
Uuid: 90a5dddb-0ebe-4a57-8d9b-1230bcfa8704
State: Peer in Cluster (Disconnected)

Hostname: 192.168.1.132
Uuid: 44da7c5d-559f-41f2-8d02-1ebd118ef829
State: Peer in Cluster (Connected)

Hostname: 192.168.1.134
Uuid: 304af68a-fd29-4bd3-845e-1cfa5bef1e59
State: Peer in Cluster (Connected)
```

Any thoughts on how to set things so the integrity of the heketi.db database and gluster is maintained.

Thanks

**Comment by iamniting** [comment]
Hi @amehub There will be 4 nodes in gluster cluster untill you issue a `heketi node delete` command. As the node remove command failed for you it did not move all bricks from it. Maybe it failed on the first brick itself. We fixed these issues some days back. I guess you are facing it because you are not using the latest heketi from the master branch. Please try it with the latest one.

**Comment by amehub** [comment]
HI @iamniting

Is this fix on dockerhub?  Does it fix the following?   gluster-04 replaced gluster-03 but gluster-04 from topology info reports that it has no bricks.   There is a brick on gluster-04.  Gluster-03 is shutdown (dead, burst into flames, gone).


```
sh-5.0# heketi-cli topology info

Cluster Id: 2e9995edf2c4fbd31d88f8e043d48ae4

    File:  true
    Block: true

    Volumes:

        Name: vol_e696f19f50412d297ae415564fe1fc23
        Size: 2
        Id: e696f19f50412d297ae415564fe1fc23
        Cluster Id: 2e9995edf2c4fbd31d88f8e043d48ae4
        Mount: 192.168.1.131:vol_e696f19f50412d297ae415564fe1fc23
        Mount Options: backup-volfile-servers=192.168.1.134,192.168.1.132,192.168.1.133
        Durability Type: replicate
        Replica: 3
        Snapshot: Enabled
        Snapshot Factor: 1.00

                Bricks:
                        Id: 036ea549140e48c1972608c06b598dd7
                        Path: /var/lib/heketi/mounts/vg_cf2ab1439915b4ee256824466e8d63fc/brick_036ea549140e48c1972608c06b598dd7/brick
                        Size (GiB): 2
                        Node: 509407651c9c0647dfc209236c7618cc
                        Device: cf2ab1439915b4ee256824466e8d63fc

                        Id: 19846d3a3466fc51b5d4fb78b0d7ddb6
                        Path: /var/lib/heketi/mounts/vg_d6289df83fac18de74ed0e0ee6e4ebd8/brick_19846d3a3466fc51b5d4fb78b0d7ddb6/brick
                        Size (GiB): 2
                        Node: 7d5826c567b1c3005f9991741a0a04f0
                        Device: d6289df83fac18de74ed0e0ee6e4ebd8

                        Id: 9e4a917f39e60a0ad245ab8ae898f96f
                        Path: /var/lib/heketi/mounts/vg_585e57cd8ddfcfd5a8b767d0b7ba0261/brick_9e4a917f39e60a0ad245ab8ae898f96f/brick
                        Size (GiB): 2
                        Node: a0da56ca7aa5d6b0a0e749f69b298076
                        Device: 585e57cd8ddfcfd5a8b767d0b7ba0261

Nodes:

        Node Id: 509407651c9c0647dfc209236c7618cc
        State: online
        Cluster Id: 2e9995edf2c4fbd31d88f8e043d48ae4
        Zone: 1
        Management Hostnames: gluster-01
        Storage Hostnames: 192.168.1.131
        Devices:
                Id:cf2ab1439915b4ee256824466e8d63fc   State:online    Size (GiB):9       Used (GiB):2       Free (GiB):7
                        Tags: tier:silver

                        Known Paths: /dev/sdb

                        Bricks:
                                Id:036ea549140e48c1972608c06b598dd7   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_cf2ab1439915b4ee256824466e8d63fc/brick_036ea549140e48c1972608c06b598dd7/brick

        Node Id: 6fbaa2e372b55c6f58ee5882e430402c
        State: online
        Cluster Id: 2e9995edf2c4fbd31d88f8e043d48ae4
        Zone: 1
        Management Hostnames: gluster-04
        Storage Hostnames: 192.168.1.134
        Devices:
                Id:00b9732da56662ed11010c1a0effbc42   State:online    Size (GiB):9       Used (GiB):2       Free (GiB):7
                        Tags: tier:silver

                        Known Paths: /dev/sdb

                        Bricks:

        Node Id: 7d5826c567b1c3005f9991741a0a04f0
        State: online
        Cluster Id: 2e9995edf2c4fbd31d88f8e043d48ae4
        Zone: 1
        Management Hostnames: gluster-02
        Storage Hostnames: 192.168.1.132
        Devices:
                Id:d6289df83fac18de74ed0e0ee6e4ebd8   State:online    Size (GiB):9       Used (GiB):2       Free (GiB):7
                        Tags: tier:silver

                        Known Paths: /dev/sdb

                        Bricks:
                                Id:19846d3a3466fc51b5d4fb78b0d7ddb6   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_d6289df83fac18de74ed0e0ee6e4ebd8/brick_19846d3a3466fc51b5d4fb78b0d7ddb6/brick

        Node Id: a0da56ca7aa5d6b0a0e749f69b298076
        State: offline
        Cluster Id: 2e9995edf2c4fbd31d88f8e043d48ae4
        Zone: 1
        Management Hostnames: gluster-03
        Storage Hostnames: 192.168.1.133
        Devices:
                Id:585e57cd8ddfcfd5a8b767d0b7ba0261   State:online    Size (GiB):9       Used (GiB):2       Free (GiB):7
                        Tags: tier:silver

                        Known Paths: /dev/sdb

                        Bricks:
                                Id:9e4a917f39e60a0ad245ab8ae898f96f   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_585e57cd8ddfcfd5a8b767d0b7ba0261/brick_9e4a917f39e60a0ad245ab8ae898f96f/brick


```

From gluster-04, 192.168.1.134 is gluster-04.

```
gluster-04:~# sudo gluster volume list                                                                                                                                                                                               [0/1021]
vol_e696f19f50412d297ae415564fe1fc23
gluster-04:~# sudo gluster volume info vol_e696f19f50412d297ae415564fe1fc23
Volume Name: vol_e696f19f50412d297ae415564fe1fc23
Type: Replicate
Volume ID: 2aa3709c-f8f2-4699-a1f5-4837d87d3c34
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 3 = 3
Transport-type: tcp
Bricks:
Brick1: 192.168.1.132:/var/lib/heketi/mounts/vg_d6289df83fac18de74ed0e0ee6e4ebd8/brick_19846d3a3466fc51b5d4fb78b0d7ddb6/brick
Brick2: 192.168.1.131:/var/lib/heketi/mounts/vg_cf2ab1439915b4ee256824466e8d63fc/brick_036ea549140e48c1972608c06b598dd7/brick
Brick3: 192.168.1.134:/var/lib/heketi/mounts/vg_00b9732da56662ed11010c1a0effbc42/brick_d797a9bd24bf8d218f4aa33af50d4c8c/brick
Options Reconfigured:
user.heketi.id: e696f19f50412d297ae415564fe1fc23
user.heketi.device-tag-match: tier=silver
transport.address-family: inet
nfs.disable: on
performance.client-io-threads: off

```

Thanks

**Comment by iamniting** [comment]
If you are using docker image use this one https://hub.docker.com/layers/heketi/heketi/dev/images/sha256-d63285bd87abfa63c01bff0533a132f6742b3781f852b9390941b61e120a0866?context=explore

**Comment by amehub** [comment]
Thank you @iamniting 

I used the image you recommended and it has fixed the heketi database so that after node replacement the correct bricks are shown on the correct nodes.  However,  in order to tidy up my gluster I want to remove the node that I "failed". I would like to clear it up from heketi but because heketi cannot reach the node (it is dead, gone) I am unable to delete the devices on the node or the delete the node itself.  Is there a heket-cli subcommand to remove an unreachable node?

Disable the devices on the dead node

```
sh-5.0# heketi-cli device disable 3dbde97f304a0594631911e831bc37cb
Device 3dbde97f304a0594631911e831bc37cb is now offline
sh-5.0# heketi-cli device disable 7fadb15eaac93e0f04ba45b01657829d
Device 7fadb15eaac93e0f04ba45b01657829d is now offline

```
Remove the devices on the dead node

```
sh-5.0# heketi-cli device remove   3dbde97f304a0594631911e831bc37cb
Device 3dbde97f304a0594631911e831bc37cb is now removed
sh-5.0# heketi-cli device remove  7fadb15eaac93e0f04ba45b01657829d
Device 7fadb15eaac93e0f04ba45b01657829d is now removed
```

Delete the devices on the dead node

```
sh-5.0# heketi-cli device delete   3dbde97f304a0594631911e831bc37cb
Error: Failed to delete device /dev/disk/by-id/lvm-pv-uuid-wmyNs3-aJrM-tG5Z-oEQF-c6Y9-3lnf-wx0PBH with id 3dbde97f304a0594631911e831bc37cb on host gluster-03: dial tcp 192.168.1.133:22: connect: no route to host
sh-5.0# heketi-cli device delete  7fadb15eaac93e0f04ba45b01657829d
Error: Failed to delete device /dev/disk/by-id/lvm-pv-uuid-Gx1H6a-eTDb-JN4J-x4iL-8jXU-d2rR-eoPQpq with id 7fadb15eaac93e0f04ba45b01657829d on host gluster-03: dial tcp 192.168.1.133:22: connect: no route to host

```

Delete the dead node

```
sh-5.0# heketi-cli node delete  4fcbc7dc1a75136c802ea4593b4e0d32
Error: Unable to delete node [4fcbc7dc1a75136c802ea4593b4e0d32] because it contains devices
```
Thanks

**Comment by phlogistonjohn** [comment]
@amehub : FWIW, I would prefer to keep the debugging particulars of your situation in an issue, but since it's already here in the PR, I'll continue the discussion.

If you're sure the node is gone you can use the --force-forget option on `heketi-cli device delete ` command. Heketi will still try to clean up the device, but even if it fails heketi will remove the device from the db. Once all devices have been removed from the node, the `heketi-cli node delete` command should execute w/o errors.

**Comment by amehub** [comment]
Hi  @phlogistonjohn

I am testing the scenario at https://github.com/heketi/heketi/pull/1783#issuecomment-694448099

The old "dead" disk device is gone and I have added a new device that I would like to use as replacement.

```
# heketi-cli device disable 65716094c87e72864c355d8d1ff58db5
Device 65716094c87e72864c355d8d1ff58db5 is now offline

```

I added new device.   The old device is physically gone.

```
sh-5.0# heketi-cli device add   --name=/dev/sdc  --node=1cad19404b5911208e13b0b73a594a3b
Device added successfully
```

The original device was /dev/sdb but this new device is /dev/sdc.

```
sh-5.0# heketi-cli device remove 65716094c87e72864c355d8d1ff58db5
Error: Unable to get heal info of volume : vol_44566b43d43b824652a7427184d4941c : Process exited with status 251
```

The device 65716094c87e72864c355d8d1ff58db5 is gone forever so try

```
sh-5.0# heketi-cli device remove 65716094c87e72864c355d8d1ff58db5 --expert-option-disable-heal-check
Skipping the heal check may be dangerous and increase the risk of data loss.
 Press CTRL-C within 10 seconds to cancel this action.
Error: Unable to delete device [65716094c87e72864c355d8d1ff58db5] as no device was found to replace it: No Replacement was found for resource requested to be removed

```

Any thoughts on how to continue to replace the "dead" disk device and get the files on the other nodes to sync to this new disk.?
From heketi-cli topology info

```
 Nodes:

        Node Id: 1cad19404b5911208e13b0b73a594a3b
        State: online
        Cluster Id: d90b95a6ad956dbe392d195b17cdce78
        Zone: 1
        Management Hostnames: gluster2-03
        Storage Hostnames: 192.168.1.143
        Devices:
                Id:0366569360862fd82a499d5449fad1a6   State:online    Size (GiB):15      Used (GiB):0       Free (GiB):15
                        Known Paths: /dev/sdc

                        Bricks:
                Id:65716094c87e72864c355d8d1ff58db5   State:offline   Size (GiB):15      Used (GiB):10      Free (GiB):5
                        Tags: tier:silver

                        Known Paths: /dev/sdb

                        Bricks:
                                Id:6cdf3f7be17466cc2e2e380f2687f27f   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_65716094c87e72864c355d8d1ff58db5/brick_6cdf3f7be17466cc2e2e380f2687f27f/brick
                                Id:de7db6fc667d3d2ecc227f42fc5e38a4   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_65716094c87e72864c355d8d1ff58db5/brick_de7db6fc667d3d2ecc227f42fc5e38a4/brick

        Node Id: 433bfdb7cd770ad9138564456045bad5
        State: online
        Cluster Id: d90b95a6ad956dbe392d195b17cdce78
        Zone: 1
        Management Hostnames: gluster2-01
        Storage Hostnames: 192.168.1.141
        Devices:
                Id:24e6d6e98db8bc3a8ecafbb102afc3e1   State:online    Size (GiB):15      Used (GiB):10      Free (GiB):5
                        Tags: tier:silver

                        Known Paths: /dev/sdb

                        Bricks:
                                Id:11b7dc777652ce3dad7a42ba59bc06c6   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_24e6d6e98db8bc3a8ecafbb102afc3e1/brick_11b7dc777652ce3dad7a42ba59bc06c6/brick
                                Id:6f0cab1c03063379f4ff1dff47a668b0   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_24e6d6e98db8bc3a8ecafbb102afc3e1/brick_6f0cab1c03063379f4ff1dff47a668b0/brick

        Node Id: 4e089465c5da8a5c073d8863b0948902
        State: online
        Cluster Id: d90b95a6ad956dbe392d195b17cdce78
        Zone: 1
        Management Hostnames: gluster2-02
        Storage Hostnames: 192.168.1.142
        Devices:
                Id:4d79dd7099cbfac344532d192bbc3e72   State:online    Size (GiB):15      Used (GiB):10      Free (GiB):5
                        Tags: tier:silver

                        Known Paths: /dev/sdb

                        Bricks:
                                Id:4583116bc954997f4fefe35c71ba410e   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_4d79dd7099cbfac344532d192bbc3e72/brick_4583116bc954997f4fefe35c71ba410e/brick
                                Id:ce9c94aeddc590f8d035cb44dfd12bf5   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_4d79dd7099cbfac344532d192bbc3e72/brick_ce9c94aeddc590f8d035cb44dfd12bf5/brick


```

Thanks

**Comment by phlogistonjohn** [comment]
> sh-5.0# heketi-cli device remove 65716094c87e72864c355d8d1ff58db5
> Error: Unable to get heal info of volume : vol_44566b43d43b824652a7427184d4941c : Process exited with status 251
> ```
> 

That's a bit odd, I thought gluster was able to get heal info for volumes even if they had missing bricks....


> The device 65716094c87e72864c355d8d1ff58db5 is gone forever so try
> 
> ```
> sh-5.0# heketi-cli device remove 65716094c87e72864c355d8d1ff58db5 --expert-option-disable-heal-check
> Skipping the heal check may be dangerous and increase the risk of data loss.
>  Press CTRL-C within 10 seconds to cancel this action.
> Error: Unable to delete device [65716094c87e72864c355d8d1ff58db5] as no device was found to replace it: No Replacement was found for resource requested to be removed
> ```

OK, so by forcing the skip of the heal check you geta different error. "No Replacement was found" errors usually indicate that no valid bricks could be created in order to fulfill the constraints on brick placement. Typically, that'd be something like not enough space, but since you just added a new device I don't think space is it.

> 
> Any thoughts on how to continue to replace the "dead" disk device and get the files on the other nodes to sync to this new disk.?
> From heketi-cli topology info
> 
> ```
>  Nodes:
> 
>         Node Id: 1cad19404b5911208e13b0b73a594a3b
>         State: online
>         Cluster Id: d90b95a6ad956dbe392d195b17cdce78
>         Zone: 1
>         Management Hostnames: gluster2-03
>         Storage Hostnames: 192.168.1.143
>         Devices:
>                 Id:0366569360862fd82a499d5449fad1a6   State:online    Size (GiB):15      Used (GiB):0       Free (GiB):15
>                         Known Paths: /dev/sdc
> 
>                         Bricks:
>                 Id:65716094c87e72864c355d8d1ff58db5   State:offline   Size (GiB):15      Used (GiB):10      Free (GiB):5
>                         Tags: tier:silver
> 
>                         Known Paths: /dev/sdb
> 
>                         Bricks:
>                                 Id:6cdf3f7be17466cc2e2e380f2687f27f   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_65716094c87e72864c355d8d1ff58db5/brick_6cdf3f7be17466cc2e2e380f2687f27f/brick
>                                 Id:de7db6fc667d3d2ecc227f42fc5e38a4   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_65716094c87e72864c355d8d1ff58db5/brick_de7db6fc667d3d2ecc227f42fc5e38a4/brick
> 
>         Node Id: 433bfdb7cd770ad9138564456045bad5
>         State: online
>         Cluster Id: d90b95a6ad956dbe392d195b17cdce78
>         Zone: 1
>         Management Hostnames: gluster2-01
>         Storage Hostnames: 192.168.1.141
>         Devices:
>                 Id:24e6d6e98db8bc3a8ecafbb102afc3e1   State:online    Size (GiB):15      Used (GiB):10      Free (GiB):5
>                         Tags: tier:silver
> 
>                         Known Paths: /dev/sdb
> 
>                         Bricks:
>                                 Id:11b7dc777652ce3dad7a42ba59bc06c6   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_24e6d6e98db8bc3a8ecafbb102afc3e1/brick_11b7dc777652ce3dad7a42ba59bc06c6/brick
>                                 Id:6f0cab1c03063379f4ff1dff47a668b0   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_24e6d6e98db8bc3a8ecafbb102afc3e1/brick_6f0cab1c03063379f4ff1dff47a668b0/brick
> 
>         Node Id: 4e089465c5da8a5c073d8863b0948902
>         State: online
>         Cluster Id: d90b95a6ad956dbe392d195b17cdce78
>         Zone: 1
>         Management Hostnames: gluster2-02
>         Storage Hostnames: 192.168.1.142
>         Devices:
>                 Id:4d79dd7099cbfac344532d192bbc3e72   State:online    Size (GiB):15      Used (GiB):10      Free (GiB):5
>                         Tags: tier:silver
> 
>                         Known Paths: /dev/sdb
> 
>                         Bricks:
>                                 Id:4583116bc954997f4fefe35c71ba410e   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_4d79dd7099cbfac344532d192bbc3e72/brick_4583116bc954997f4fefe35c71ba410e/brick
>                                 Id:ce9c94aeddc590f8d035cb44dfd12bf5   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_4d79dd7099cbfac344532d192bbc3e72/brick_ce9c94aeddc590f8d035cb44dfd12bf5/brick
> ```
> 
> Thanks

Looks like you have tags applied to the other devices. Do you have tag matching rules set up on the volumes? If so, the tag matching rules on a volume apply even for brick replacement. Look to see if those volumes have tag matching rules and if so try applying tags to the new device like you have on the old, and then retry the operation.

You may want to retry without the  `--expert-option-disable-heal-check` option. It is not there for down nodes, its there for scalability issues in some older versions of gluster. It could be worth trying to figure out why you got heal errors too.

**Comment by amehub** [comment]
Hi 

Thanks for getting back to me.   I deleted and recreated the new device with the correct tag.  this time different error.    The device is gone from the node.  Perhaps remove expects to be able to access the device that is being removed. 

```
[root@d100de83c300 heketi]# heketi-cli device remove 65716094c87e72864c355d8d1ff58db5
Error: Error destroying brick [&{{6cdf3f7be17466cc2e2e380f2687f27f /var/lib/heketi/mounts/vg_65716094c87e72864c355d8d1ff58db5/brick_6cdf3f7be17466cc2e2e380f2687f27f/brick 65716094c87e72864c355d8d1ff58db5 1cad19404b5911208e13b0b73a594a3b 44566b43d43b824652a7427184d4941c 5242880} 5242880 28672 0 {b8647025e1607701b9126ecf18c06413} tp_54cbc507332757de7a8997bec062d1be  1}]: umount: /var/lib/heketi/mounts/vg_65716094c87e72864c355d8d1ff58db5/brick_6cdf3f7be17466cc2e2e380f2687f27f: target is busy.
```

```
[root@d100de83c300 heketi]# heketi-cli device remove 65716094c87e72864c355d8d1ff58db5
Error: Error destroying brick [&{{6cdf3f7be17466cc2e2e380f2687f27f /var/lib/heketi/mounts/vg_65716094c87e72864c355d8d1ff58db5/brick_6cdf3f7be17466cc2e2e380f2687f27f/brick 65716094c87e72864c355d8d1ff58db5 1cad19404b5911208e13b0b73a594a3b 44566b43d43b824652a7427184d4941c 5242880} 5242880 28672 0 {b8647025e1607701b9126ecf18c06413} tp_54cbc507332757de7a8997bec062d1be  1}]: umount: /var/lib/heketi/mounts/vg_65716094c87e72864c355d8d1ff58db5/brick_6cdf3f7be17466cc2e2e380f2687f27f: target is busy.
[root@d100de83c300 heketi]# heketi-cli device remove 65716094c87e72864c355d8d1ff58db5
Error: The target exists, contains other items, or is in use.


```

**Pull request merged**
