### PR TITLE
tests: add some unit tests

### PR DESCRIPTION
**Pull request by phlogistonjohn**
These tests check for error conditions that I created when I was doing preliminary untangle work.

### CODE REVIEW

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
The travis run strangely keeps failing.
Has something changed in the travis env itself?

It seems the bash logic of
```
if [[ -z "$COVERAGE" ]]; then make test TESTOPTIONS=-v ; fi
if [[ -n "$COVERAGE" ]]; then make test TESTOPTIONS=-vcstdout && bash .travis-coverage; fi
```
is broken in that the one where the condition is false, the whole command fails.

**Comment by phlogistonjohn** [comment]
'Twas a go formatting oopsie. Fixed.

**Comment by obnoxxx** [comment]
@phlogistonjohn wrote:
> 'Twas a go formatting oopsie. Fixed.

Oh, really? I was too stupid to see that in the travis output. It seemed to me that that one of the two "if" statements that did not apply failed. And other PRs failed the same way. (Hence PR #1004.) So what was that? Some glitch in the travis env? *confused*

**Comment by obnoxxx** [comment]
Ok, now searching for *fmt* I see it...

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
retest this please

(now the centos-ci should be fixed again)

**Comment by obnoxxx** [comment]
retest this please

**Comment by phlogistonjohn** [comment]
retest this please

**Comment by obnoxxx** [comment]
centos-ci test failure is unrelated. moving on...

**Pull request merged**
