### PR TITLE
Logging: Node and device delete conflict message to be logged

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Closes: #608 
Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
@heketi/dev please review

**Comment by obnoxxx** [comment]
@centos-ci ok to test

**Comment by obnoxxx** [comment]
network flakey?

@centos-ci retest this please

**Comment by obnoxxx** [comment]
lgtm but want the tests to pass

**Comment by MohamedAshiqrh** [comment]
Looks like not with respect to patch.

```
==> ERROR: unable to start vagrant virtual machines
==> FAILED TestVolumeSnapshotBehavior
==> TEARDOWN TestVolumeSnapshotBehavior
```

**Comment by obnoxxx** [comment]
ok on the more powerful machine I see the "volume create" failure, on the less powerful one, it succeeds .... may be a race

**Comment by obnoxxx** [comment]
running functional tests locally...

**Comment by obnoxxx** [comment]
verified func test locally

**Pull request merged**
