### PR TITLE
Update GLOCKFILE

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: hchiramm <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@lpabon not sure why travis is keep failing. can you please check this PR and do the necessary changes in GLOCKFILE ?

**Comment by lpabon** [comment]
That is because the new code brings in your Sudo support.  you will have to fix #299 before fixing this one.  See: https://travis-ci.org/heketi/heketi/jobs/131111152#L295

**Comment by lpabon** [comment]
Probably when you fix #299 this one will be fixed also.

**Comment by lpabon** [comment]
@humblec Make this change in the sudo patch and abandon this one.  That should make it work.

**Comment by humblec** [comment]
Clsoing this PR as this has been addressed in https://github.com/heketi/heketi/pull/353

**Pull request closed without merging**
