### PR TITLE
apps:glusterfs: make it possible to get disperse volumes with 1 brick…

### PR DESCRIPTION
**Pull request by obnoxxx**
… set only

Signed-off-by: Michael Adam <obnox@samba.org>

### CODE REVIEW

**Comment by obnoxxx** [comment]
Just as we did for replicate volumes: this makes it possible to obtain volumes with just one brickset.

**Comment by obnoxxx** [comment]
@centos-ci please test

**Comment by obnoxxx** [comment]
gosh how do I do that with @centos-ci  ? :-)

**Comment by obnoxxx** [comment]
@centos-ci ok to test

**Comment by lpabon** [comment]
@obnoxxx The commands are in https://github.com/heketi/heketi/wiki/Testing , but I wonder if it only listens to me.  We'll check with Niels next week

**Comment by lpabon** [comment]
ok to test @centos-ci

**Comment by obnoxxx** [comment]
@lpabon ok, thanks. I had @centos-ci react to me once before, but this time, strangely, it didn't ...

**Comment by obnoxxx** [comment]
And I was looking other  PRs, but @github strangely cheats on us by removing items from the history in PRs ... :-o

**Pull request merged**
