### PR TITLE
Heketi logs to both stderr and heketi.log

### PR DESCRIPTION
**Pull request by ramkrsna**
Initial commit to see to log to a file along with the stderr works #552

### CODE REVIEW

**Comment by ramkrsna** [comment]
I'll rework this, I need to send in a Test Case for  this patch

**Comment by MohamedAshiqrh** [comment]
@obnoxxx Please close this. @ramkrsna after rework create a new PR.

**Comment by obnoxxx** [comment]
@MohamedAshiqrh why a new pr? @ramkrsna should rework and then update?

( @ramkrsna should be able to close himself if he thinks it's appropriate.. ) :-)

**Comment by MohamedAshiqrh** [comment]
@obnoxxx after seeing the initial commit there were few commented lines present and edit in vendor code. next commit will be changes on this commit. So then this PR has to be dropped anyways(just wanted to keep it clean).

**Pull request closed without merging**
