### PR TITLE
tests: do not fetch go binaries if not needed

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Change the functional tests so they support only fetching go binaries
if needed. Use the HEKETI_TEST_SYSTEM_GO variable to allow the user
to tweak this behavior. The value of this variable can be yes, no, or
auto. Auto will only fetch go binaries if the version number is older
than 1.8.3, and is the default behavior.

Signed-off-by: John Mulligan <jmulligan@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
a strange vagrant  error -- box not found?

retest this please

**Comment by obnoxxx** [comment]
retest this please

**Comment by obnoxxx** [comment]
retest this please

**Comment by phlogistonjohn** [comment]
retest this please

(was another failure to set up the test vms)

**Comment by obnoxxx** [comment]
Not clear what failed really. All I see is passed tests... @phlogistonjohn any clue?

**Comment by phlogistonjohn** [comment]
This seems to be the culprit, but I don't see the cause yet:
```
Heketi v5.0.0-287-ge9e15cb-pr_1002
[heketi] INFO 2018/02/08 19:11:27 Loaded ssh executor
=== RUN   TestConnection
--- FAIL: TestConnection (0.00s)
	assert.go:44: 
		
ASSERT:	func (github.com/heketi/heketi/tests/functional/TestVolumeSnapshotBehavior/tests.TestConnection) 0x6bcacd
		
	File /root/go/src/github.com/heketi/heketi/tests/functional/TestVolumeSnapshotBehavior/tests/heketi_test.go:220
		
	Info: [Get http://127.0.0.1:8080/hello: dial tcp 127.0.0.1:8080: getsockopt: connection refused]
=== RUN   TestHeketiVolumeSnapshotBehavior
--- FAIL: TestHeketiVolumeSnapshotBehavior (0.00s)
	assert.go:44: 
		
ASSERT:	func (github.com/heketi/heketi/tests/functional/TestVolumeSnapshotBehavior/tests.teardownCluster) 0x6bc7d5
		
	File /root/go/src/github.com/heketi/heketi/tests/functional/TestVolumeSnapshotBehavior/tests/heketi_test.go:131
		
	Info: [Get http://127.0.0.1:8080/clusters: dial tcp 127.0.0.1:8080: getsockopt: connection refused]
FAIL
exit status 1
FAIL	github.com/heketi/heketi/tests/functional/TestVolumeSnapshotBehavior/tests	0.009s
==> storage3: Removing domain...
==> storage2: Removing domain...
==> storage1: Removing domain...
==> storage0: Removing domain...
/root/go/src/github.com/heketi/heketi/tests/functional/TestVolumeSnapshotBehavior/../lib.sh: line 12:  1770 Terminated              $HEKETI_SERVER --config=config/heketi.json  (wd: ~/go/src/github.com/heketi/heketi/tests/functional/TestVolumeSnapshotBehavior)
==> FAILED TestVolumeSnapshotBehavior
```

**Comment by obnoxxx** [comment]
oh, right ... not sure why i missed it. I could have sworn I grepped for ASSERT ... ;-)

**Comment by obnoxxx** [comment]
retest this please

**Pull request merged**
