### PR TITLE
Adding ppc64le support

### PR DESCRIPTION
**Pull request by Pensu**
Hi all,

This PR adds support for ppc64le builds.

### CODE REVIEW

**Comment by nixpanic** [comment]
ok to test

**Comment by phlogistonjohn** [comment]
I have mixed feelings about this. One one hand it's a small change that enables you to more easily build for your systems (I assume). On the other hand I don't want advertise that we "support" any of these architectures that we don't regularly test on. Because it's such a small change I could just suggest you run `make dist GOOS=linux GOARCH=ppc64le`

In theory, golang just magically deals with these architectures but you know what they say about theory. I personally want to remove some of the OS & Arches that are currently part of the build. Someone please convince me that I'm going overboard. :-)

**Comment by nixpanic** [comment]
We do provide Heketi for all architectures that Fedora supports. Those
packages get built on the actual architectures, and not through
cross-compiling like 'make release' does. I can not think of a good
reason to not provide the packages, and hope that the theory of Golangs
portability holds.

https://koji.fedoraproject.org/koji/buildinfo?buildID=1089123

**Comment by phlogistonjohn** [comment]
> We do provide Heketi for all architectures that Fedora supports. Those packages get built on the actual architectures, and not through cross-compiling like 'make release' does. I can not think of a good reason to not provide the packages, and hope that the theory of Golangs portability holds.

OK. I still think we should stop "releasing" binaries for stuff I doubt anyone ever uses (heketi darwin build I'm looking at you). But that's not what this PR is asking for so I'll buy it.

**Comment by nixpanic** [comment]
On Fri, Jul 27, 2018 at 09:37:41AM -0700, John Mulligan wrote:
> > We do provide Heketi for all architectures that Fedora supports. Those packages get built on the actual architectures, and not through cross-compiling like 'make release' does. I can not think of a good reason to not provide the packages, and hope that the theory of Golangs portability holds.
> 
> OK. I still think we should stop "releasing" binaries for stuff I doubt anyone ever uses (heketi darwin build I'm looking at you). But that's not what this PR is asking for so I'll buy it.

I also hope that people explicitly asking for these extra architectures
do test the resulting binaries, and update them when there is a new
release ;-)

**Comment by Pensu** [comment]
@nixpanic @phlogistonjohn Thanks for the reviews. We do use heketi quite a bit for ppc64le, both for development and production. So we are covered good for testing. And I am ready to provide support or update whenever the new release happens. :)

**Comment by phlogistonjohn** [comment]
@Pensu that's great to hear! I'm curious how you have gluster deployed for your cluster?

**Comment by Pensu** [comment]
@phlogistonjohn We have gluster running as pods internally and everything is on ppc64le itself.

**Comment by Pensu** [comment]
@phlogistonjohn @nixpanic Can we get this merged?

**Comment by nixpanic** [comment]
I'm still ok with getting this merged. Heketi is built and distributed by the CentOS Storage SIG for ppc64le already too. The following is expected to 'just work' on CentOS ppc64le:

```
yum install centos-release-gluster
yum install heketi
```

**Comment by guirish** [comment]
@nixpanic  @Pensu ,
 
Any updates on this PR merger? I want raise a PR on cross build and release support for s390x too.

**Comment by phlogistonjohn** [comment]
This PR has been (substantively) stale for nearly a year now. Closing.

**Pull request closed without merging**
