### PR TITLE
CLI instance for heketi server

### PR DESCRIPTION
**Pull request by MohamedAshiqrh**
Closes: #318 

Created a new instance of heketi server cli in cobra to avoid unknown flags importation.

Signed-off-by: Mohamed Ashiq Liyazudeen <mliyazud@redhat.com>

### CODE REVIEW

**Comment by MohamedAshiqrh** [comment]
@heketi/maintainers please review.

**Comment by MohamedAshiqrh** [comment]
Fun fact: My first patch from flight ;P.  Wanted to do this for a long time.

**Comment by MohamedAshiqrh** [comment]
Output:
```

# heketi --version
Heketi v3.0.0-101-g9b14392-server-cli

# heketi -h
Heketi is a restful volume management server

Usage:
  heketi [flags]

Examples:
heketi --config=/config/file/path/

Flags:
      --config string   Configuration file
  -v, --version         Show version

# heketi --help
Heketi is a restful volume management server

Usage:
  heketi [flags]

Examples:
heketi --config=/config/file/path/

Flags:
      --config string   Configuration file
  -v, --version         Show version

# heketi --config=/heketi.json
Heketi v3.0.0-101-g9b14392-server-cli
[heketi] INFO 2017/02/08 01:46:37 Loaded mock executor
[heketi] INFO 2017/02/08 01:46:37 Loaded simple allocator
[heketi] INFO 2017/02/08 01:46:37 GlusterFS Application Loaded
Listening on port 3333
^CShutting down...
[heketi] INFO 2017/02/08 01:46:38 Closed
```

**Comment by MohamedAshiqrh** [comment]
I checked the errors but not sure tests are passing on my local.

**Comment by MohamedAshiqrh** [comment]
Figured it -config was hardcoded in python api testing.
Fixed it.

**Comment by MohamedAshiqrh** [comment]
Found few more references and changed all to posix compliant flags. just like our heketi server cli.

**Comment by MohamedAshiqrh** [comment]
Yay...! It worked!

**Comment by MohamedAshiqrh** [comment]
@heketi/dev @heketi/maintainers please review.

**Comment by lpabon** [comment]
Looks great!  Just tested

**Pull request merged**
