### PR TITLE
Ensure pending volumes filter works on delete operations

### PR DESCRIPTION
**Pull request by phlogistonjohn**
### What does this PR achieve? Why do we need it?

The functions used to filter out pending volumes and block volumes were not correctly checking for all cases where a pending operation was indicating that a volume or block volume was pending & incomplete.

### Does this PR fix issues?

Fixes [rhbz#1662141](https://bugzilla.redhat.com/show_bug.cgi?id=1662141)

### Notes for the reviewer

It is now possible for a volume to go pending for delete and then be unmarked pending if the delete fails. This implies that it is possible for a volume to vanish from the listing and then reappear some time later. This is a bit odd but I don't think this behavior is worse than failing the listing commands because a pending delete operation is in the db.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
retest this please

**Comment by phlogistonjohn** [comment]
centos-ci failure appears due to flaky test. Will start another run, but please don't wait for that to succeed for reviews thanks.

**Comment by phlogistonjohn** [comment]
retest this please

**Comment by phlogistonjohn** [comment]
retest this please

**Comment by obnoxxx** [comment]
the centos-ci failure seems to be entirely unrelated

**Comment by obnoxxx** [comment]
I think I have spotted a possible way of reducing the flakyness of this test. will check and possibly file a separate PR for improving that.

**Pull request merged**
